### ISSUE TITLE
turbo-frame tage with 'src' attribute not adding proper mimetype to fetch request

### ISSUE THREAD

**Issue by sebscholl** [hotwired/turbo#1013]
I'm using turbo in rails, and have a view with the following tag:

```erb
  <%= turbo_frame_tag 'organizations', src: '/organizations' %>
```

I then have a `index.turbo_stream.erb` view for updating the originating tag:

```erb
  <%= turbo_stream.replace 'organizations' do %>
    <ul>
       // not relevant
    </ul>
<% end %>
```

When the page loads the tag loads the source, however it does not attach the `Accept: text/vnd.turbo-stream.html` and Rails fails to recognize the request as a `turbo_stream` request. As a result, the `respond_to` block return HTML as opposed to the turbo stream template.

```rb
  def index
    @organizations = @current_user.organizations

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
```

I was able to get the expected behavior to work by manually adding the Accept header on the `turbo:before-fetch-request` event and setting a custom `type='turbo-stream'` attribute on the tag. However, I feel like this is either a bug, or I'm missing a configuration.

```js
document.addEventListener('turbo:before-fetch-request', (event) => {
  if (event.target.getAttribute('type') == 'turbo-stream') {
    event.detail.fetchOptions.headers['Accept'] = 'text/vnd.turbo-stream.html';
  }
})
``` 

Is this expected for the `src` attribute?

**Comment by seanpdoyle** [comment]
Thank you for opening this issue!

I believe you're combining two distinct concepts. A Turbo Frame with a `[src]` attribute will transmit a `GET` request for `text/html` content. That request should be handled by the server as HTML. You can learn more about frames in the [Decompose with Turbo Frames](https://turbo.hotwired.dev/handbook/frames) section of the Turbo Handbook.

Your server response should treat the request as HTML, and respond as if it were a typical full-page HTML request. When Turbo receive the response, it'll search the response HTML for a `<turbo-frame>` element with a matching `[id]` attribute and replace its old contents with the response's contents.

Requests originating from a `<turbo-frame>` won't have the `text/vnd.turbo-stream.html` because they're conceptually separate from `<turbo-stream>` elements and Turbo Stream responses. You should not inject an `Accept: text/vnd.turbo-stream.html` header into a Turbo Frame's request.
