### ISSUE TITLE
Turbo Frame stays in loading state after being replaced by a previous turbo frame

### ISSUE THREAD

**Issue by javierav** [hotwired/turbo#1059]
When I visit `/day/energy` page, rails returns the following view:

```html
<ul>
  <li><a class="text-red-700" href="/day/energy">Report for day</a></li>
  <li><a class="" href="/month/energy">Report for month</a></li>
  <li><a class="" href="/year/energy">Report for year</a></li>
</ul>

<turbo-frame data-turbo-action="advance" id="metrics" src="/metrics/energy/day">
  <p>Loading metric energy...</p>
</turbo-frame>
```

It returns an eager-loaded turbo frame to parallelize the loading of a section with higher computational cost. When page loads, Turbo perform a GET request to `/metrics/energy/day` page that returns the following view:

```html
<turbo-frame data-turbo-action="advance" id="metrics">
  <h3>Metric energy for day</h3>
  <ul>
    <li><a href="/day/energy">Energy</a></li>
    <li><a href="/day/power">Power</a></li>
    <li><a href="/day/costs">Costs</a></li>
  </ul>
</turbo-frame>
```

When I click on any of the links (inside "metrics" turbo frame) to change the type of reports, for example in Power link, Turbo perform a GET request to `/day/power` and the cycle repeats as at the beginning: rails returns the following view:

```html
<ul>
  <li><a class="text-red-700" href="/day/energy">Report for day</a></li>
  <li><a class="" href="/month/energy">Report for month</a></li>
  <li><a class="" href="/year/energy">Report for year</a></li>
</ul>

<turbo-frame data-turbo-action="advance" id="metrics" src="/metrics/power/day">
  <p>Loading metric power...</p>
</turbo-frame>
```

Due to presence of `src` attribute, Turbo perform a GET request to `/metrics/power/day` that returns:

```html
<turbo-frame data-turbo-action="advance" id="metrics">
  <h3>Metric power for day</h3>
  <ul>
    <li><a href="/day/energy">Energy</a></li>
    <li><a href="/day/power">Power</a></li>
    <li><a href="/day/costs">Costs</a></li>
  </ul>
</turbo-frame>
```

But this last turbo frame not is replaced and the "Loading metric power" text remains displayed...

Whats happen here?

Demo: https://turbo-frame-issue.aranda.dev/
Source: https://github.com/javierav/turbo-frame-issue

May be related with #581

**Comment by brunoprietog** [comment]
What happens is that Turbo expects the src of a Turbo Frame to be used only the first time, or otherwise changed via JavaScript. When Turbo makes the request associated with a Turbo Frame, it will only replace that Turbo Frame with the content of the other Turbo Frame that comes in the response. It will not touch anything in the turbo-frame element itself, Except for the src attribute, which is set to the page on which the visit ended from which the new Turbo Frame content was obtained, and other things such as the complete attribute. So when you return to the main page, the original src of the Turbo Frame is never set (/metrics/energy/day). Instead, the src will be the page URL that the Turbo Frame was directed to, which would be the main page in this case (/day/energy). When you browse Turbo Frames, you should only expect what is inside them to change, but not the element itself. I hope I have explained well. I think this is the intended behavior anyway.
