### ISSUE TITLE
data-turbo="false" doesn't seem to work

### ISSUE THREAD

**Issue by mbajur** [hotwired/turbo#119]
Hello!
I'm trying to migrate one of my turbolinks apps to turbo and i encountered an issue with one of the features. Basically, i have a sign-out link which signs user out and redirects him to a page that returns a 401 HTTP status.

The thing is, even though this sign-out link has a `data-turbo="false"` set up, i can still see the request is being done in the background by Turbo, user gets signed out successfully but page never refreshes and i can see a warning message about 401 in javascript console. If it changes anything, this link also has `data-method="delete"` attribute. So basically, if i'm getting it well, `data-turbo="false"` does not really disables Turbo for this specific link. 

I'm on 7.0.0-beta.3

***

EDIT: I just encountered an exact same issue but with a form that redirects to a different page. Form gets submitted in the background, response is a 302 with a redirect to different path but from user perspective - nothing is happening. Even with `data-turbo="false"` or `data-turbo-drive="false"` set on that form.

**Comment by seanpdoyle** [comment]
>  If it changes anything, this link also has `data-method="delete"` attribute

Is your project also making use of RailsUJS? If it is, and the link annotated with `data-remote="true"`, then UJS might be submitting the request instead of Turbo Drive.

**Comment by mbajur** [comment]
thank you for reply @seanpdoyle , it was indeed caused by the UJS. I am using a library called bootstrap_form and apparently setting `remote: false` argument for `bootstrap_form_with` doesn't set data-remote attribute properly.

**Comment by ghiculescu** [comment]
@seanpdoyle is this expected if you aren't using `remote: true`?

For example, this link:

```ruby
= link_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: "false" }
```

Is being processed by Turbo. (We do have UJS running as well.)

**Comment by seanpdoyle** [comment]
Hmm, that's surprising @ghiculescu. Could you try to reproduce this with the [skip-iframe-targets](https://github.com/hotwired/turbo/tree/skip-iframe-targets) branch? (https://github.com/hotwired/turbo/pull/66)

**Comment by ghiculescu** [comment]
Hmmm. Not sure that will work either (though I will test it).

- `data-method` creates a form - https://github.com/rails/rails/blob/main/actionview/app/assets/javascripts/rails-ujs/features/method.coffee#L32 - but doesn't set any attributes (eg `data-turbo`) on it.
- your PR calls `elementIsNavigable` on form submissions: https://github.com/hotwired/turbo/pull/66/files#diff-2924f9b9b352387b2055c51f7cee79918af463f55bdbc50313b0733b362b7013R41 (similar to current Turbo), but the form doesn't have any special attributes on it to trigger the `data-turbo: false` behavior.

![image](https://user-images.githubusercontent.com/509837/105548720-9d29b100-5cc5-11eb-8348-c49f7f3cbf0e.png)

**Comment by ghiculescu** [comment]
Looking at this more closely I suspect rails-ujs would need to be updated to handle this, unless you can think of a better solution?

**Comment by seanpdoyle** [comment]
@ghiculescu I'm confused. Are you calling `link_to` or `button_to`?

I was thinking of this line: https://github.com/hotwired/turbo/pull/66/files#diff-ee7f6f631993fd72de3499d4661589cf37ab3347cac0d4bb76eca549b7db8726R39

that moves the guard against `<a data-turbo="false">` up a level to occur a little sooner, and I was curious if that resolved your issue.

**Comment by ghiculescu** [comment]
@seanpdoyle `link_to`. I missed that line though. Let me test.

**Comment by ghiculescu** [comment]
@seanpdoyle same issue.

**Comment by ghiculescu** [comment]
I added a breakpoint at the line you gave me. When you click the link, you get this backtrace:

![image](https://user-images.githubusercontent.com/509837/105552080-1080f200-5cc9-11eb-910b-a3fb20625c41.png)

But `link` is null:

![image](https://user-images.githubusercontent.com/509837/105552122-1bd41d80-5cc9-11eb-9f1d-1458363dc9ba.png)

Because `event.target` is the `input` created by rails-ujs:

![image](https://user-images.githubusercontent.com/509837/105552161-2b536680-5cc9-11eb-80a7-ce1b7756b6b3.png)

So the handler here is already being ignored.

The problem is that a `<form>` was created by rails-ujs, which means this code (that I linked above) runs:

![image](https://user-images.githubusercontent.com/509837/105552378-6eadd500-5cc9-11eb-8e09-628e55d8fd75.png)

The highlighted line returns `true` which means the Turbo behavior happens.

**Comment by seanpdoyle** [comment]
@ghiculescu ahh, I think I understand now. Are you citing the fact that UJS constructs a `<form>` element entirely through JS?

Does replacing the `link_to` with a `button_to` that accepts the `data: { turbo: "false" }` attribute work? That way, you can achieve the same behavior without relying on an `<a>` to encode an HTTP verb, and you have direct control over the HTML that gets constructed.

**Comment by ghiculescu** [comment]
omg. not only does it work, it's even [documented](https://github.com/hotwired/turbo-rails#compatibility-with-rails-ujs) 😭

Sorry to waste your time here @seanpdoyle and thank you for stepping through it with me.

**Comment by ghiculescu** [comment]
Proposed some more docs: https://github.com/hotwired/turbo-rails/pull/91

@dhh is Rails UJS in maintenance mode, or would a PR to add Turbo compatibility be accepted? Specifically, I'd like to copy the `data-turbo` attribute from the [link](https://github.com/rails/rails/blob/main/actionview/app/assets/javascripts/rails-ujs/features/method.coffee#L9) to the [form](https://github.com/rails/rails/blob/main/actionview/app/assets/javascripts/rails-ujs/features/method.coffee#L15) so that you can do `data-turbo=false` on `data-method` links.

**Comment by seanpdoyle** [comment]
A [polyfill of sorts was proposed](https://github.com/hotwired/turbo/pull/40), but we decided it didn't fit within Turbo itself. I'm not sure on what would be the most appropriate home for it.

I think documentation is a step in the right direction!

**Comment by rmm5t** [comment]
I'm confused. Has anyone considered patching rails/ujs to always copy all data-attributes (except for `data-remote` or `data-method` etc) from the anchor tag (`link_to`) to the generated form element? That would copy all `data-turbo` attributes along with anything else that might make sense for the underlying form to adhere to.

**Comment by seanpdoyle** [comment]
Without digging in, one thing that might pose a problem is whether or not that UJS-created `<form>` element is ever "mounted" onto the page. If it's an orphaned node, I'm not sure if the checks and event listeners that Turbo wires up will be aware of its submission lifecycle.

@rmm5t that concern aside, that sounds like a good idea!

**Comment by rmm5t** [comment]
@seanpdoyle Thanks. Another idea I had was to modify rails/ujs to append the generated form element to the link's parent node instead of the body node. This might only work for the `Rails.handleMethod` behavior, but this would allow you to wrap a `link_to ... method: :post` with something like a `<span data-turbo="false">` as a workaround for areas where it wouldn't work by applying data-turbo directly to the link.

**Comment by rmm5t** [comment]
> _whether or not that UJS-created <form> element is ever "mounted" onto the page. If it's an orphaned node_

@seanpdoyle Yes, the form is "mounted" to the page, and it can be picked up by Turbo. I've already tested this with a monkey-patch to the `Rails.handleMethod` function. Right now, it's appended to the `body`, but like my 2nd suggestion, it might be better to append to the link's parent node, which then potentially avoids the need to copy all the data attributes.
