### ISSUE TITLE
Navigating to page with non-successful response seems to reload javascript

### ISSUE THREAD

**Issue by RemcodM** [hotwired/turbo#1190]
We are using Turbo Drive 7.3.0, but is also happens on our 8.0.2 branch that we are working on.

In some cases, when navigating with Turbo Drive, we can navigate to a page returning a non-successful error response, such as a error 403 because the user has no permission to that page.

When this happens, Turbo does not seem to keep track of the script tags in the header correctly. They seem to be evaluated on top of the existing JavaScript, causing all kinds of issues, such as: `Uncaught SyntaxError: redeclaration of const ...`

We are using `data-turbo-track="reload"` on our scripts, however, the assets have not been changed between the requests. So we do not expect a reload at all.

The problem does not seem to occur once we return the forbidden page with a successful response code (200). Once we change it back to 403, or even 404, 400 or 500, the problem returns.

**Comment by afcapel** [comment]
@RemcodM can you provide a minimal rails app showcasing the problem?

**Comment by Ambient-Impact** [comment]
I've also been seeing the same re-evaluation of scripts on [our Drupal site](https://refreshless.omnipedia.app/): you can trigger the re-evaluation by going to any article (e.g. [the Omnipedia article](https://refreshless.omnipedia.app/wiki/2049/10/01/Omnipedia)) and clicking the Edit tab which gives you a 403 error; after navigating to one or two other 200 response links, you'll start seeing the console debug messages duplicate. I can try and put together a reduced test case when I have some time.

**Comment by Ambient-Impact** [comment]
I just poked around in the Firefox dev tools a bit to try and see what's going on, and what I noticed is that the `<head>` element in the 200 response pages is no longer in the DOM after a visit to the 4xx page, where a different `<head>` element is present - I have no idea why this would be happening, but it would certainly explain the re-evaluation of scripts if it is indeed a new `<head>` element being added to the DOM with the `<script>` elements from the previous visit already present.

**Comment by afcapel** [comment]
Yes, Turbo [does this intentionally ](https://turbo.hotwired.dev/handbook/drive#reloading-when-assets-change)when you mark a script tag with `data-turbo-track="reload"`. It's the only way to ensure the client runs the latest JS after a deploy.

**Comment by afcapel** [comment]
I'm going to close this, since it seems expected behavior. But feel free to reopen with a test case if you find a bug.

**Comment by afcapel** [comment]
Seems that you have a meta tag with data-turbo-track="reload"?

<img width="747" alt="Screenshot 2024-02-21 at 15 50 58" src="https://github.com/hotwired/turbo/assets/150107/f24ae892-e9fe-4ad7-b3c0-32151cc1eb64">

I'd try removing it and see if that helps. But, also, as I said, happy to reopen the issue if you can provide a minimal reproduction.

**Comment by Ambient-Impact** [comment]
@afcapel I just tried removing it but it had no effect. That meta tag only ever changes when navigating between the site front-end and admin sections, where the Drupal theme changes and it does force a full page load as it's supposed to, so I would have been surprised if it had an effect. I appreciate you getting back to me, and I'll see if I can throw together a minimal reproduction.

**Comment by Ambient-Impact** [comment]
So I did some debugging in dev tools and discovered that the `ErrorRenderer` class always replaces the `<head>` outright:

https://github.com/hotwired/turbo/blob/861fcca4eed3b2d97240284e99eafeb43d55fca5/src/core/drive/error_renderer.js#L18

This probably makes sense for some apps, but in our cases it seems like it's creating a weird in between state where a full page load has not occurred so scripts executed previously still linger in the JavaScript environment but the scripts get re-evaluated by `ErrorRenderer`:

https://github.com/hotwired/turbo/blob/861fcca4eed3b2d97240284e99eafeb43d55fca5/src/core/drive/error_renderer.js#L13

In our Drupal app, the 4xx pages contain the same linked JavaScript files as most other pages, so this means Turbo re-evaluates all the same JavaScript files on an error response.

The full stack trace:

```
replaceHeadAndBody (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#3719)
render (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#3713)
renderSnapshot (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#1535)
render (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#1495)
renderError (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#4985)
loadResponse (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2506)
render (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2710)
loadResponse (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2495)
visitRequestFailedWithStatusCode (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2780)
recordResponse (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2482)
requestFailedWithResponse (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2616)
receive (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#856)
perform (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#831)
issueRequest (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2458)
visitStarted (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2751)
start (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2408)
startVisit (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#3290)
visitProposedToLocation (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#2742)
visitProposedToLocation (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#5337)
proposeVisit (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#3280)
visit (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#5201)
followedLinkToLocation (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#5326)
clickBubbled (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#1635)
clickCaptured (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#1624)
start (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#1610)
start (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#5155)
start (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#5602)
<anonymous> (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#6573)
<anonymous> (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#8)
<anonymous> (https://omnipedia.ddev.site/modules/contrib/refreshless/modules/refreshless_turbo/vendor/%40hotwired/turbo/dist/turbo.es2017-umd.js?v=8.0.2#9)
```

Using that clue, I took a look at `Visit.loadResponse()`:

https://github.com/hotwired/turbo/blob/861fcca4eed3b2d97240284e99eafeb43d55fca5/src/core/drive/visit.js#L219

and replaced that line with:

```js
const snapshot = PageSnapshot.fromHTMLString(responseHTML);
await this.renderPageSnapshot(snapshot, false);
```

reloaded the page, and bingo, it no longer re-evaluates all of our JavaScript no matter how many 4xx error pages I visit.

---

Given that, is there a way to configure Turbo to use the normal renderer rather than the error renderer?

**Comment by fschwahn** [comment]
@afcapel we are running into the same issue: we are rendering our error pages in the full application layout (ie. also the complete `<head>` with all javascript files) from our normal pages. This leads to our entire javascript being loaded twice (eg. all click handlers are there 2 times, etc.)

I tried following your advice and removed all `data-turbo-track` attributes, but this does not make a difference. It still double loads the Javascript code:
<img width="359" alt="image" src="https://github.com/user-attachments/assets/b3f0a042-f22c-49fc-b185-591e8896d876">

I don't think this problem is related to `data-turbo-track`. Do you have any pointers how to create a minimal test case? I believe it should be simple (just a JS file which is loaded in both the normal visit and the error visit which sets a global `const` should be sufficient).

I looked if I can somehow force a hard-reload on error pages, but I couldn't find a solution which worked in all cases:
- `<meta name="turbo-visit-control" content="reload">` does not seem to work as the ErrorRenderer does not seem to pick it up
- using `turbo:before-fetch-response`-event was tricky due to prefetching

It would be great if I could indicate in a response header that a full page visit should happen, but I haven't found such a thing.

**Comment by trsteel88** [comment]
Having the same issue here. We're using the reload attribute too but that should fully reload the page? Instead, we're seeing the same javascript execute which means we have multiple event listeners firing (e.g. Turbo sets itself up multiple times). On the next request we then see 2 turbo requests, then 3, and it just keeps growing.

Did you end up finding a solution @fschwahn?

**Comment by fschwahn** [comment]
What we ended up with is:

```js
  document.addEventListener("turbo:before-fetch-response", function (event) {
    const { status } = event.detail.fetchResponse.response;

    // Check for <html>-tag to ensure we don't redirect when we are merely prefetching a link (in that case the target is the link itself).
    if (event.target.tagName === "HTML" && status >= 400) {
      event.preventDefault();
      window.location.href = event.detail.fetchResponse.response.url;
    }
  });
```

**Comment by trsteel88** [comment]
Thanks @fschwahn I was thinking the same. This seems like a bug to me and I don't know why this is closed. Turbo shouldn't just load additional javascript as it causes existing event listeners to pile up.

**Comment by domchristie** [comment]
This definitely feels like a bug, and @Ambient-Impact's [comment](https://github.com/hotwired/turbo/issues/1190#issuecomment-1957369921) suggests why.

It's never been clear why error responses need their own renderer; could they use `PageRenderer`?

With that in mind, here's a patch that will use `PageRenderer`:

```js
window.Turbo.session.view.constructor.prototype.renderError = function renderError(snapshot, visit) {
  return this.renderPage(snapshot, false, true, visit)
}
```

(I'm not sure what the side effects are, but it does appear to fix this issue.)

**Comment by domchristie** [comment]
See also: https://github.com/turbolinks/turbolinks/issues/179

**Comment by domchristie** [comment]
> [@RemcodM](https://github.com/RemcodM) can you provide a minimal rails app showcasing the problem?

@afcapel here's a demo: https://github.com/domchristie/turbo_error_test

**Comment by domchristie** [comment]
It's also worth noting that I think this bug is only present when loading your application JavaScript in the traditional way i.e. _not_ as `<script type="module …>`. The browser seems to not re-execute module-type JavaScript files when Turbo reactivates them.

`<script defer …>` has similar behaviour to `<script type="module" …>` (see below) so if you're currently using `defer`, you may want to try switching to `type="module` instead.

![Image](https://github.com/user-attachments/assets/add2bfd5-87be-4276-a626-86f48ca29658)
Diagram from the [HTML Living Standard](https://html.spec.whatwg.org/multipage/scripting.html#:~:text=This%20is%20all%20summarized%20in%20the%20following%20schematic%20diagram:)
