### ISSUE TITLE
Turbo 8 data-turbo-action=advance and turbo stream replaces head section

### ISSUE THREAD

**Issue by AlfonsoUceda** [hotwired/turbo#1203]
Hello everyone thank you for making turbo amazing.

I am experiencing a weird behaviour when upgrading to Turbo v8 from v7, this is the code I have:

**View**
```html
<turbo-frame id="id_1">
  <a data-turbo-action="advance" data-turbo-frame="id_1" data-turbo-stream="true" />
</turbo-frame>
```
**Controller**
```ruby
def action
  respond_to do |format|
    format.turbo_stream do
       render html: html
    end

    format.html do
      ...
    end
  end
end
```

In v7 this works perfect but after upgrading to v8 it doesn't works very well. The reason that I think it does not work well and could be a possible bug is that when I receive the response Turbo replaces the HTML correct but the head section is replaced too and several tags are removed.

My question is, why does it replace the `head` section if I haven't provided any head tag in the response? Is this beaviour expected? 

I've tried to understand what the changes are related to this change but I haven't found anything.

**Comment by brunoprietog** [comment]
Hi, this is certainly not the expected behavior, but there is a confusion of concepts here. Actions marked with `data-turbo-stream` will not be treated as a visit, so you shouldn't expect it to change the URL or point to a Turbo frame. A request marked as a Turbo stream should respond with Turbo streams, which can invoke certain actions. But that's it, they don't replace anything, they don't point to Turbo frames or make modifications to the browser history.

So, if you just keep the Turbo stream things, i.e. remove `data-turbo-action` and `data-turbo-frame`, the same thing happens? Also, this would require you to add an `href` attribute to the `<a>` element.

**Comment by AlfonsoUceda** [comment]
@brunoprietog than you for your answer. For now we are going to refactor our code to make it properly work with Turbo and remove the `data-turbo-stream` for now unless an action is used.

Thanks!
