### ISSUE TITLE
`src` attribute is not removed from turbo-frame after loading content

### ISSUE THREAD

**Issue by joyheron** [hotwired/turbo#1307]
## Actual Behavior

When the response to a submit from within a Turbo Frame is a redirect, the content of the new Turbo Frame is retrieved by setting the `src` attribute of the Turbo Frame to the redirect URL (that seems to happen here: https://github.com/hotwired/turbo/blob/main/src/core/session.js#L102 ). Once the content has been loaded, however, the `src` attribute is not removed but remains on the new `<turbo-frame>` element.

## Expected Behavior

I expected that the `src` attribute would be removed from the Turbo Frame once the content from the redirect has been loaded, since the new Turbo Frame does not have a `src` attribute.

## Background

This is causing issues for me when using a different JavaScript library with no knowledge of Turbo (this one: https://github.com/innoq/tabelle) because the other library removes the Turbo Frame node from the DOM and then reinserts it. Because the `src` attribute isn't removed after the content of the Frame is loaded, once the Turbo Frame is reinserted in the DOM, Turbo (understandably) thinks that the `src` attribute needs to be retrieved from the Server and does so. This results in an infinite loop where (1) Turbo retrieves a resource from the server and replaces the content of the Frame, (2) the JavaScript library shuffles the DOM and removes and reinserts the Turbo Frame into the DOM, then (3) go back to (1)

It took me a while to track down this issue because I wasn't manually setting any `src` attributes on my Turbo Frames, so I couldn't figure out where the `src` attribute in the DOM of the `<turbo-frame>` was coming from.

**Comment by brunoprietog** [comment]
This is by design. The Turbo frame will only consider the attributes of the element when rendering it for the first time. After that, the element is only used to look up the Turbo frame reference, but the element is not modified. The src attribute corresponds to the URL to which the Turbo frame navigated and is also not removed nor is it appropriate to do so.

If you want to set specific attributes on a Turbo frame, you must make sure that those attributes are in the first rendering of the Turbo frame. If that can happen on multiple pages, you should duplicate them.

Additionally, including a Turbo frame as a direct child of the table or thead, tbody or tfooter element is invalid HTML, so it won't work either. That is, you cannot have one Turbo frame per row.

I recommend you to include the element inside the children of the Turbo frame element, if that is the use case. When navigating the Turbo frame, the element should be able to recover, because it is disconnected and a new element is connected.
