### ISSUE TITLE
No migration path for data-turbolinks-temporary="true"

### ISSUE THREAD

**Issue by mildred** [hotwired/turbo#179]
In Turbolinks there is the option to have the attribute `data-turbolinks-temporary="true"`, especially for notifications. This attribute does not seems to be there with Turbo Drive. How to migrate this attribute?

**Comment by sstephenson** [comment]
`data-turbolinks-temporary` was a feature of [Turbolinks 3.0](https://github.com/turbolinks/turbolinks-classic), added in 2015 and never officially released: https://github.com/turbolinks/turbolinks-classic/commit/b4ad476b5538e99a15c907a33002c5c208ea2fcc 

It hasn't been in Turbolinks/Turbo since the rewrite for version 5.

Can you explain how you're using it?
