### ISSUE TITLE
404 causes DOMException

### ISSUE THREAD

**Issue by iamdriz** [hotwired/turbo#188]
I'm using the latest version of Turbo (beta 4 at the time of writing) and I've noticed that when you hit a 404 page it causes the following error in the console:
```js
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "turbo-frame" has already been used with this registry
```
This only happens when hitting a 404 from another link... if you refresh the non existent page the error doesn't happen.

**Comment by iamdriz** [comment]
If it helps here's a screenshot of exactly what happens in the console when the navigation to the non existent page happens:
![image](https://user-images.githubusercontent.com/801252/108910545-eef38d00-761d-11eb-9174-e48399412728.png)

**Comment by morindo** [comment]
I'm having the same problem.

**Comment by clinejj** [comment]
This looks to be a similar issue from Turbolinks: https://github.com/turbolinks/turbolinks/issues/179

Essentially Turbo handles 404/500 pages differently, and ends up re-rendering the page and initializing itself twice which leads to these errors. Unfortunately, the monkey patch from the issue above doesn't work on Turbo (or I can't get it to work at least)

**Comment by clinejj** [comment]
I opened https://github.com/hotwired/turbo-rails/issues/249 as this seems to be more of an issue with turbo-rails than Turbo, and the specific use case we're able to replicate on is using a custom error controller that has the same layout as our main application which includes turbo. Because the ErrorRender in Turbo reloads both the body and head, it leads to turbo-rails and turbo being initialized twice. It seems that Turbo is protected from this ([here](https://github.com/hotwired/turbo/blob/318d8aae00823f672db2df4f5975c04429f6bf07/src/core/session.ts#L45)), but turbo-rails is not.

**Comment by tydoo** [comment]
Same problem with 7.0.1

**Comment by markdavies** [comment]
I am seeing the same issue in a non-Rails setup

**Comment by erosinlove** [comment]
Same problem with 7.1.1

**Comment by kmmbvnr** [comment]
I fixed this with `data-turbo-eval="false"` on the script tag with turbo bundle

```
<script src="{% static 'viewflow/js/turbo.es5-umd.js' %}" data-turbo-eval="false"></script>
```

**Comment by denydias** [comment]
This one is indeed a showstopper for anything handling 4* and 5* errors.

As @clinejj observed above, the monkey patch didn't work and it'll never work with Turbo. It turns out that [HttpRequest method was removed](https://github.com/hotwired/turbo/commit/522a0609d98c391b4c1a34147b5394ed6d9bed74) altogether. But rather than he also pointed out, it's not turbo-rails related. My PHP app also suffers with the same 4* and 5* handling issues.

It would be really nice from Turbo devs if they could elaborate a bit on the reasoning behind to HttpRequest removal. It would even nicer from their part if a workaround could be provided... It doesn't even need to be funcional code tho. A shallow overview would suffice for devs like us to figure out the rest.

**Comment by kidlj** [comment]
I changed `import * as Turbo from "@hotwired/turbo"` to `require("@hotwired/turbo")`, the problem is gone.

**Comment by kidlj** [comment]
I'm having the same problem with `"@hotwired/turbo": "^7.1.0"`, not on Rails framework. 

After changing 

```
import "@hotwired/turbo"
```

from index.js to 

```
if (!window.Turbo) {
	require("@hotwired/turbo")
}
```

The problem is gone, but the 404 page would flash a bit, not as smooth as normal pages.
