### ISSUE TITLE
Add option to deactivate Turbo Drive

### ISSUE THREAD

**Issue by renestalder** [hotwired/turbo#190]
Currently, Turbo assumes that the whole framework is used from the point on it is imported. But as the whole Turbo Drive is immediately activated, this can break whole websites even though the developer might only use Turbo Frames. 

**We should either have an option to independently import the modules (#136) or for example, being able to deactivate Turbo Drive.**

Sadly, `<meta content="reload" name="turbo-visit-control">` is not enough as Turbo Drive still intercepts the native page loading and can still break things, for example, scrolling, as it scrolls to top while fetching the next page, which for example can cause an issue like wrong scroll positions with smooth-scroll CSS properties active.

**Comment by sstephenson** [comment]
If you want to opt-out of Turbo Drive on all links and forms, you can add `data-turbo="false"` to any containing element. (The `<html>` or `<body>` elements should work.)

https://turbo.hotwire.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms

**Comment by gregschmit** [comment]
I had this issue, but I think I submitted it to the wrong repo: https://github.com/hotwired/turbo-rails/issues/139

**Comment by gregschmit** [comment]
@sstephenson  To clarify my position, I don't think this issue is resolved with `<html data-turbo="false">`, because some projects want to use Turbo in the context of frames/streams and either have lots of layouts and/or layouts that are on customer systems which are controlled by customers so the developer that manages the JS backend (like webpacker) wants to disable Drive by default and allow customers to opt-in.

**Comment by renestalder** [comment]
Isn't the documentation stating that this is for Turbo Drive? I at least assuming that, which means, my frames should still run even though they are nested in a parent that has `data-turbo="false"`, and if so, that at least resolves my original issue. If I misunderstand that, then yes, my issue might not be resolved.

**Comment by gregschmit** [comment]
@renestalder Yeah I didn't word my last comment carefully enough: your issue is resolved in teh sense that if you put `data-turbo="false"` it will disable Turbo Drive, without affecting Frames/Streams. I was just pointing out that it would be nice to disable it from the JS backend rather than having to change each and every layout file in potentially large projects or projects where layouts are defined by customers and where you don't want to break existing stuff.

My PR would allow the JS backend to disable Drive by default, so the user would use `data-turbo="true"` to enable Drive on selected elements, making the behavior opt-in, rather than opt-out, just like how the rest of the framework operates.

**Comment by Petercopter** [comment]
@renestalder

> Turbo Drive still intercepts the native page loading and can still break things, for example, scrolling, as it scrolls to top while fetching the next page, which for example can cause an issue like wrong scroll positions with smooth-scroll CSS properties active.

This is now a bigger issue because Bootstrap 5 defaults to using `scroll-behavior: smooth`. I started an issue in the turbo-rails repo, but I should probably move it here: https://github.com/hotwired/turbo-rails/issues/165

Is disabling either the smooth scrolling or Turbo the only option? Can they live together happily?

**Comment by anthony0030** [comment]
Fix for turbo & bootstrap that causes the page to scroll to the top before load.
This works because aria-busy gets added to the html before the turbo starts to take you to the next page.
```CSS
  html[aria-busy="true"] {
    scroll-behavior: auto !important;
  }
```

**Comment by andrewclapham** [comment]
I'm also frustrated by Turbo Drive. I have a lot of jQuery code that is specific to each page. It would be great to be able to disable turbo drive so that everything doesn't break, without disabling turbo streams.
