### ISSUE TITLE
Load a dropdown only once

### ISSUE THREAD

**Issue by seb-jean** [hotwired/turbo#205]
Hi :),

I wanted to know how to load a dropdown only once.

For Hey, if we click once, there is a call. However, there is no call the second time.

Thanks :)

![20210312_100302](https://user-images.githubusercontent.com/12116264/110918844-e6889b00-831b-11eb-8697-7c2f477ddf0f.gif)

**Comment by danmcge** [comment]
When you open that dropdown, there is some javascript that sets the `src` attribute. That triggers the frame to be loaded, because frames listen for changes to `src` to work out when to load a URL. When you open the dropdown for the second time, the same javascript runs, but the `src` attribute doesn’t change. It was already set to the URL, the content has been already been loaded. So the frame won’t load anything again.

Questions like this should go to [the forum](https://discuss.hotwire.dev) really, rather than GitHub. As this isn’t an issue, it shouldn’t be on the issue tracker. I think it should be closed.
