### ISSUE TITLE
5xx Responses trigger full reload for form submissions.

### ISSUE THREAD

**Issue by thanosbellos** [hotwired/turbo#234]
Hello.

I am using:

- Rails  6.1.3.1
- turbo-rails 0.59
- turbo v7.0.0beta4

I noticed that if i visit some Turbo enabled links that may tigger a 5xx response, we see the classic page informing us about the server error (i.e)

<img width="993" alt="Screenshot 2021-04-08 at 3 46 34 PM" src="https://user-images.githubusercontent.com/425283/114028880-a1f01100-9881-11eb-819a-5f18feb76e05.png">

When i submit a form to create, update or delete a resource, that may trigger a 5xx response, we don't get the same response. The page fully reloads and the submission failure error is written on the browser console.  That seems, to be related to the fact that the response headers do not include the same assets,  turbo detects that change and triggers a full reload on the page. But that is not happening for the first use case (link navigation).

In fact if we remove data-turbo-track=reload,  then even form submission will result in the error page.

After searching around the codebase i found that in normal turbo visit navigation, error responses are handled by an ErrorRenderer:

https://github.com/hotwired/turbo/blob/db96ea903b50e1ae3ceef89a7285ef7a52657dad/src/core/drive/visit.ts#L203

https://github.com/hotwired/turbo/blob/db96ea903b50e1ae3ceef89a7285ef7a52657dad/src/core/drive/page_view.ts#L23

After form submission, it is handled by the  PageRenderer that will check for asset changes and reload if there are any changes
https://github.com/hotwired/turbo/blob/db96ea903b50e1ae3ceef89a7285ef7a52657dad/src/core/drive/navigator.ts#L94

Is there any possibility we could have the same behaviour for form submissions? Or is it something that i should handle somehow at application level?( i took the idea from the test here: https://github.com/hotwired/turbo/blob/4670f2b57c5d0246dfc0f6d10ff7d9a52a63fdca/src/tests/fixtures/500.html)

 #208 is definitely related.

Thanks a lot for your time

**Comment by pinzonjulian** [comment]
I can report that this is still happening.

In my case I created a simple scaffold for a `Post` model.
```ruby
class PostsController < ApplicationController
  def new
    #...
  end
  def create
    raise
  end
end
```

Upon submitting the form I am not presented with the default error page. Instead the current page gets refreshed.

@dhh I wanted to bring this to your attention since I've seen a lot of activity recently in the hotwire repos. I believe it's an important thing to get sorted out before cutting a final release of the library.

I believe there are multiple issues and PR's related to this:

https://github.com/hotwired/turbo/issues/326
https://github.com/hotwired/turbo/pull/210
https://github.com/hotwired/turbo/issues/208
https://github.com/seanpdoyle/turbo/commit/03dc8c1e71383ecd5208e5b726e52dd957239ca5

As a Rails developer, my expectation is that if a form submission returns an uncaught exception the page does not randomly refresh. By default, I expect to get redirected to the Exception's page in development and to a `error 500` page in prodcution.

I'll try to create a PR with a failing test but in the meantime I'd appreciate any comments on this. 

Thanks!
