### ISSUE TITLE
Turbo frame navigation after following a form redirection is break when the URL has been visited before.

### ISSUE THREAD

**Issue by sukei** [hotwired/turbo#245]
Hello, please note that this behavior has changed since the beta-5. Instead of trying to explain the issue, I'm going to describe the behavior I'm facing.

- I have a link that target a frame with `data-turbo-frame="my-id"`.
- When I click to this link, a request is issued. Then, the `<turbo-frame id="my-id">` is successfully updated and its `src` attribute too.
- I have some forms within the frame (a multi-step wizard in fact), when I submit the forms, I'm redirected to the next step, and since the beta-5, the `src` attribute of the frame is updated too. Everything is good so far, I'm very grateful for this one.
- But now, When I click to the original link, no request is issued and the frame remains on the wizard step URL.

My guess: The frame keep somewhere the state of the current active URL and didn't trigger a query when the same one is requested again. But, this state is not updated when following form redirection. So, when a link that match the current state is clicked again, the frame didn't move.

**Comment by nielsslot** [comment]
I ran into, what I think is, this as well. And I think I've narrowed down the problem.

First, a quick and dirty way to reproduce:

- Create a new Rails app, install Turbo
- Generate a simple scaffold: `rails g scaffold post title:string`
- Add `app/views/posts/_show.html.erb` with the following contents:
```erb
<turbo-frame id="<%= dom_id(post) %>">
  <div>
    <%= post.title %>
    <%= button_to('Edit', edit_post_path(post), method: :get) %>
  </div>
</turbo-frame>
```
- Add the following at the end of `app/views/posts/edit.html.erb`:
```erb
<turbo-frame id="<%= dom_id(@post) %>">
  <%= form_for(@post) do |f| %>
    <%= f.text_field :title %>
    <%= f.submit 'Save' %>
  <% end %>
</turbo-frame>
```
- Add `<%= render partial: 'show', collection: @posts, as: :post %>` to posts index view and `<%= render partial: 'show', locals: { post: @post } %>` to posts show view (not the partial)
- Now start the Rails server, open up a browser to `/posts` and use the scaffold to create a new post. 
- Go to the index page and use the edit button in the frame to edit the post title inline and save it
- Because of this issue you can't edit the post again without refreshing the page first

I narrowed the problem down to the update of the `src` attribute after redirects in `frame_controller.ts`. While the `sourceURL` variable does get updated after a redirect, the `currentURL` does not. `FrameController` only performs a load when `sourceURL` and `currentURL` are different. And since `currentURL` is still, incorrectly, set to the previous page and `sourceURL` is being set back to that value (because we want to navigate there again), both values are the same and no loading happens.

A simple fix that works for me is to add an extra check and assignment to `currentURL` in `FrameController#loadSourceURL`:
```javascript
  async loadSourceURL() {
    if(this.settingSourceURL) {
      this.currentURL = this.sourceURL;
    }

    if (!this.settingSourceURL && this.enabled && this.isActive && this.sourceURL != this.currentURL) {
      // ...
    }
  }
```

That updates the `currentURL` variable when the `sourceURL` is updated after a redirect.

**Comment by strobilomyces** [comment]
I'm assuming this is the same issue. Before beta-5, I noticed that when a child frame is targeted, rather than updating the frame with the same id, Turbo nests a new child frame within the first. This goes on infinitely for every action. I never reported it because everything still worked fine, despite the DOM weirdness. Now, however, as described in the posts above, after one click, it nests and the action does nothing.

This is a screenshot I took from beta-4. The beta-5 version is simply a child with one nested child.

![de3344e3cf09a81522d992b37f6edb80](https://user-images.githubusercontent.com/68540841/114844229-e0825000-9dda-11eb-82f0-3d07ea8b9c84.png)

**Comment by janko** [comment]
We've encountered this issue as well, attempting to visit a link previously loaded in the turbo frame doesn't load the page into the turbo frame (the `src` attribute gets correctly updated, but no new HTTP request is being made).

This bug seems to be present only with links, form submit with redirect seems to work correctly even if the redirect URL has previously been visited.

The workaround we've made is to add a random query parameter to the link that fails to get visited, so that the turbo frame `src` is always different, e.g: `edit_user_path(user.id, t: Time.now.to_i)` (which produces links like `/users/123?t=1621934807`).

**Comment by tortuetorche** [comment]
> We've encountered this issue as well, attempting to visit a link previously loaded in the turbo frame doesn't load the page into the turbo frame (the src attribute gets correctly updated, but no new HTTP request is being made).

I think this bug is still present with Turbo 7.0.0-beta.7 and the scenario above, or it's just me? 🤷‍♂️

**Comment by DustinArmstrong** [comment]
Since others didn't share their controller markup here I'm not sure if this is 100% the same problem, but in case encounters this later I found **this happens for us when the controller rendered rather than redirected** which I hadn't considered seen mentioned anywhere else.

```ruby
# Doesn't work
def update
  if @room.update(room_params)
    render :show
  else
    render :edit
  end
end
```
```ruby
# Works
def update
  if @room.update(room_params)
    redirect_to @room
  else
    # Requires an additional turbo_stream file which you can read about here:
    #   https://github.com/hotwired/turbo/issues/138#issuecomment-847699281
    render :edit
  end
end
```
