### ISSUE TITLE
Obsolete data when using Turbo Streams with concurrency?

### ISSUE THREAD

**Issue by tpetry** [hotwired/turbo#25]
In normal web applications, multiple users often work on the same resources (unlike hey.com). In today's world of video conferencing, it is even more common for a web application to be used by multiple people in parallel.

With Turbo Streams, updated versions of resources can now be displayed live to all users without a page reload. It's a big step towards a fully collaborative application! But how does Turbo Streams deal with simultaneous updates of Turbo Frames now? Let's assume two users both submit a form pretty much simultaneously without any conflicts. The response may already include an update to the Turbo Frame so they can see their update, but now other users' changes are also distributed via the websocket and due to temporary delays in the backend, the last version sent via websocket may be an outdated version that is then displayed.

This can be illustrated with the following example:
1. _User A (A)_ submits form
2. _User B (B)_ submits form
3. Data of _A_ is committed
4. Data of _B_ is committed
5. Calculation after commit of data requires a moment longer for _A_, because something else is executed and temporary takes longer
6. _B_ receives http response for http request with new turbo frame from committed data of _B_ which is displayed
7. _A_ receives http response for http request with new turbo frame from committed data of _A_ which is displayed
8. Turbo stream sends turbo frame by web socket for modification of _B_
9. Turbo stream sends turbo frame by web socket for modification of _A_

Now the displayed information is incorrect because the turbo frame with the changed information of user A and not B is displayed, although the data of B is the persistent one in the database. These problems do occur in reality as race conditions are possible in the backend execution. Is there any logic planned to solve this problem? You could e.g. include e.g. an optional timestamp or commit version number (or any incrementing value) in the dom specification for turbo frames to ensure the chronological sorting, so that received turbo frames with an older version can be discarded by the JavaScript code.

This may be possible to integrate with custom logic, but it is such an essential part that it should be part of the core and not be implemented by everyone?

**Comment by dhh** [comment]
Turbo stream sends actions, like append or replace, rather than frames (that's sorta a separate technique). Some actions a idempotent, like remove, and others, like append/prepend, generally do not have timing issues. But replace definitely could. It's not a problem we've seen cause much/any trouble in the wild, so not something we've focused on, but your theoretical case is correct. 

Please do investigate a peak into a solution. Given the rarity/low criticality in most cases, though, there probably isn't appetite for a very complicated/invasive built-in solution to this. But maybe there's something simple we can do.
