### ISSUE TITLE
discuss.hotwire.dev stopped working

### ISSUE THREAD

**Issue by tleish** [hotwired/turbo#300]
discuss.hotwire.dev greets you with different messages depending on refreshing and attempts to interact.

<img width="680" alt="https___discuss_hotwire_dev" src="https://user-images.githubusercontent.com/1099993/124290983-4dbb9c80-db11-11eb-969b-4010b6b97b6f.png">

<img width="803" alt="Version_1_Documentation_of_Stimulus__-_General_-_Hotwire_Discussion" src="https://user-images.githubusercontent.com/1099993/124290995-514f2380-db11-11eb-8ead-5f3f27757748.png">

Likely related to https://github.com/hotwired/turbo/issues/292

**Comment by dhh** [comment]
Yeah, working with @samsaffron to resolve this. Shouldn't be long.

**Comment by dhh** [comment]
All fixed, and we now have it running on a new domain: https://discuss.hotwired.dev.

**Comment by Obversity** [comment]
@dhh Is this a permanent change? I'm struggling to login with github at the moment, here's the url it sends me back to.

https://discuss.hotwire.dev/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=asdf

The params are somewhat enlightening, the oauth redirect URL probably needs to be fixed in Github's app setup? I'm unsure.

Google results are very much broken as well. If y'all still own the old URL, you might be able to use google's ["change of address"](https://support.google.com/webmasters/answer/9370220?hl=en) tool, although I don't know much about it or how well it works.

**Comment by michelson** [comment]
can confirm that the OAuth access have a redirect URI mismatch, it should be fixable by editing the OAuth app at Github/google

**Comment by dhh** [comment]
Working with @samsaffron to get the login issue fixed. Thanks for reporting.
