### ISSUE TITLE
Turbo Drive treats external URLs redirected from same-origin URLs as same-origin

### ISSUE THREAD

**Issue by TastyPi** [hotwired/turbo#401]
According to the Turbo Drive docs https://turbo.hotwired.dev/handbook/drive#setting-a-root-location:

> By default, Turbo Drive only loads URLs with the same origin—i.e. the same protocol, domain name, and port—as the current document. A visit to any other URL falls back to a full page load.

However, I have encountered two scenarios where this is not the case:

1. Form POST request to same-origin returns a 303 redirect response to another domain
2. An anchor with a link to a same-origin URL returns a 303 redirect response to another domain

In both cases, Turbo Drive attempted to load the external URL, which in my particular case causes a CORS error due to cross-origin requests not being allowed by the external page. I've fixed both cases by adding `data-turbo=false` to the `<form>` and `<a>` respectively, but based on the wording of the documentation I would have expected them to both fallback to a full page load.

Is it possible for Turbo Drive to handle redirects in the expected way?

**Comment by ghiculescu** [comment]
Turbo Drive tells its underlying `fetch` request to follow redirects: https://github.com/hotwired/turbo/blob/c9c1c11610f12442a6342200e396c12a30ed957d/src/http/fetch_request.ts#L120

I think the problem is that Turbo can't know ahead of time if the page will redirect to a third party URL. So it has no way of knowing it if should send a `fetch` or not.

https://developer.mozilla.org/en-US/docs/Web/API/fetch suggests there's an alternative option (`manual`) which I suppose could be supported instead, it'd be a fair bit more code to support redirects rather than letting the browser do it for us.

![image](https://user-images.githubusercontent.com/509837/134253866-6dc08933-1241-4cfc-a45b-561c01d514d9.png)

**Comment by TastyPi** [comment]
Makes sense, I figured it would be something to do with automatically follwing redirects. If someone (maybe me, not sure if I have the time) did contribute a pull request which changed the behaviour, would it be likely to be accepted or would it be rejected due to adding too much complexity for a corner case like this? I'm fine with my solution of disabling Turbo if it wouldn't, but it might be worth at least updating the docs to mention this corner case.

**Comment by ghiculescu** [comment]
I think a docs PR is a good start. I’m not a maintainer so can’t answer the other question. My gut feel is this isn’t a very common case, as you say.

**Comment by mxlje** [comment]
I have the same problem. In my case I want to redirect users to an external payment provider during the checkout, and the URL has to be generated on the server.

Disabling Turbo technically works, but then I am also losing the ability to disable the button using the turbo events (to prevent double clicking), for example.

My current workaround is to use Stimulus and a turbo stream:

```js
import { Controller } from 'stimulus'

export default class extends Controller {
  static values = {
    url: String
  }

  connect() {
    window.location.href = this.urlValue
  }
}
```

```erb
<%= turbo_stream.update :payment do %>
  <%= tag.div nil, data: {
    controller: "location-href",
    location_href_url_value: @url
  } %>
<% end %>
```

The page with the button has an empty `<div id="payment">`, which then receives the controller through the stream. It’s not ideal but it works and for me is better than disabling turbo.

**Comment by edwinv** [comment]
We also experience this issue. We use `data-method="post"` for actions that make changes in the database. Some of these changes result in a redirect url which the user needs to visit, like a payment url or a oauth flow. For `GET` requests, we easily can disabled Turbo with `data-turbo="false"`. For `POST` requests, there is no alternative because this feature is only available through Turbo. Changing the method to `GET` is not ideal due to the nature of the requests.

Ideally Turbo handles a redirect to a cross-origin location correctly. This doesn't seem to be that easy because with a `fetch` you can't handle the redirect yourself. Maybe the service-side could render a same-origin response that Turbo handles to load the new location. But that's not perfect either because Turbo is backend agnostic.

I'd love to hear @dhh his opinion on this. I expect a lot of Rails users upgrading to Turbo going to experience this issue. Maybe we should at least update the documentation for this, but maybe there are other approaches possible?

**Comment by boboldehampsink** [comment]
In my case, a form with method POST and an external action is also processed through Turbo. This shouldn't be happening, according to this?:

> By default, Turbo Drive only loads URLs with the same origin—i.e. the same protocol, domain name, and port—as the current document. A visit to any other URL falls back to a full page load.

**Comment by TastyPi** [comment]
@boboldehampsink that sounds like a different issue, this issue is specifically about redirects from same-origin to external. I suggest you open a new issue.

**Comment by boboldehampsink** [comment]
@TastyPi indeed, sorry. Opened a new issue for that (https://github.com/hotwired/turbo/issues/435)

**Comment by sagzy** [comment]
@TastyPi thanks for the workaround! Worked for us

**Comment by andrewjtait** [comment]
We also have an issue with this problem.

Similar to others, we have a form which can POST and update data. When there are errors we want Turbo to update the form for the user, but on success we want to follow a returned redirect to an external URL.

So disabling Turbo on this form fixes the redirect, but it does not provide a very good experience when there are form errors.

**Comment by TastyPi** [comment]
@andrewjtait we have a new solution that allows us to do both. We created a very basic Stimulus controller that uses JavaScript to redirect, and we use Turbo to add an element using that controller to the DOM

```javascript
export default class extends Controller {
  static values = {url: String}

  def initialize() {
    window.location.href = this.urlValue
  }
}
```

```html.erb
<%# create.turbo_stream.erb %>
<%= turbo_stream.append "form" do %>
  <%= tag.div data: {controller: "redirect", redirect_url_value: @url} %>
<% end %>
```
It's not ideal, but it works.

**Comment by TastyPi** [comment]
I created a small Rails apps with examples of how to set up redirection at https://github.com/TastyPi/turbo-forms

**Comment by sedubois** [comment]
I ended up here after attempting to change our existing Stripe Checkout client-side redirect ([redirectToCheckout](https://stripe.com/docs/js/checkout/redirect_to_checkout), which used to be their only option available) into a server-side redirect (as shown [above](https://github.com/hotwired/turbo/issues/401#issuecomment-934355345)). Our intention is to avoid the extra render and accelerate the transition to the checkout page. We want to keep XHR in the order form to allow displaying validation errors (so data-turbo should be true), but if validation passes it should redirect to the external Stripe checkout page. As noted here however, we encounter 403 Forbidden, "CORS Missing Allow Origin": `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://checkout.stripe.com/pay/cs_test_XXX (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`.

**Comment by dhh** [comment]
If anyone wants to summarize these challenges in a doc PR, that would be a good start. It's a basic CORS restriction, so I think treating validation errors with JS and then using vanilla forms for the redirect is a good path to suggest.

**Comment by fritzmg** [comment]
Couldn't this be automated via error handling within Turbo instead?

**Comment by natematykiewicz** [comment]
A simple solution is to use Turbo Power's [redirect_to Stream Action](https://github.com/marcoroth/turbo_power-rails/blob/f852ce5b5a8a439e34269cb609a88526bd7669a8/lib/turbo_power/stream_helper.rb#L239-L241).

```ruby
respond_to do |format|
  format.html { redirect_to url, allow_other_host: true }
  format.turbo_stream { render turbo_stream: turbo_stream.redirect_to(url) }
end
```

In our case we have a Stripe Checkout flow that requires you to sign in / sign up before proceeding to Stripe for payment. Redirecting to Stripe caused a CORS error, but we didn't want to have to disable Turbo on every form in the sign in / sign up flow just because it **_might_** inevitably redirect to Stripe.

Instead, the action that _**does**_ redirect to Stripe now returns a Turbo Stream to tell the browser to navigate to the Stripe Checkout URL. Turbo is on the whole time, and no CORS errors happen.

**Comment by lapser** [comment]
See also https://github.com/hotwired/turbo-rails/issues/483#issuecomment-2363583421
