### ISSUE TITLE
Bug: Cached Preview Rendered After New Content

### ISSUE THREAD

**Issue by jakemumu** [hotwired/turbo#481]
I've not been able to figure out why / how this is happening, but we're using Hotwire / turbo along with Devise. Devise has been patched to always return unprocessable entity or redirect on success or failures, which works great -- the one weird part is when we logout via a get request (probably the simplest method) -- we redirect to the homepage on the website. When I put prints into the turbo drive callbacks, I see the NEW content flash, before the preview / cached content is then displayed. 

So for some reason, in this instance, the cached content is rendering AFTER the new content. Has anyone seen this? 

Thanks, 

J

**Comment by tleish** [comment]
What version of turbo are you using?

**Comment by jakemumu** [comment]
in my package.json `"@hotwired/turbo-rails": "^7.0.1",`
& in my gemfile.lock: ` turbo-rails (0.8.3)`

Are there any recommendations on how I could help debug what's happening? I've not debugged a js package installed via Webpacker before. -- I can however confirm when I disable previewing on the website the issue goes away via: 

`<meta name='turbo-cache-control' content='no-preview'>`

**Comment by tleish** [comment]
The reason I ask, there was a similar issue reported and fixed in the latest release (see https://github.com/hotwired/turbo/issues/447).

You may want to try to set the versions to the latest in your manifest files.

- `"@hotwired/turbo-rails": "^7.1.0"`
- `turbo-rails (0.9.0)`

Also, it's helpful to verify the actual javascript version in your package-lock.json or yarn.lock file?

**Comment by jakemumu** [comment]
let me give this a shot today and report back : )

**Comment by jakemumu** [comment]
Nice! manually bumping to `7.1.0` appears to fix it, thank you!
