### ISSUE TITLE
data-turbo-method with redirect 

### ISSUE THREAD

**Issue by jcoyne** [hotwired/turbo#492]
When you have a link that has `data-turbo-method="DELETE"` and it returns a 302 status, then turbo loads the new page with the same method as the initial request.  I believe it should be a GET request. 

This shows the problem:
<img width="892" alt="Screen Shot 2021-12-06 at 2 39 44 PM" src="https://user-images.githubusercontent.com/92044/144919544-54e0b26f-5199-4e87-9a29-116216887efd.png">

I am using version 7.1.0.

**Comment by seanpdoyle** [comment]
Responding to [Form Submissions](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission) with an HTTP verb other than `GET` or `POST` requires a [303 See other](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303).

If the response has a `303` (instead of a `302`), does it behave as you'd expect?

**Comment by jcoyne** [comment]
@seanpdoyle yes, that is what I wanted. Thank you so much. This comment was helpful to me: https://github.com/hotwired/turbo/issues/84#issuecomment-756189909  I was confused as this is a change from how Rails-ujs handles 302 and that the `redirect_to` method in rails does a 302 by default.
