### ISSUE TITLE
Adding  <meta name="turbo-visit-control" content="reload"> causes every link to issue two requests.

### ISSUE THREAD

**Issue by ChrisZou** [hotwired/turbo#513]
I use Vue on one of my project. In order to ease the pain of integrating with turbo drive, I added 

```
<meta name="turbo-visit-control" content="reload">
```

to the head section of my application layout. But then I found that every link on the site would issue two requests instead of one. You can see it on the "Network" panel of develop tools and also the server log.

I also made a demo project and can reproduce this problem [here](https://github.com/ChrisZou/notes/commits/main). You can checkout [this commit](https://github.com/ChrisZou/notes/commit/5e260f2df9384d095e0d8e09d1d6a1174adc65cc). 
Create a note and on the note index page, click "Show this note" and observe the server log.

![image](https://user-images.githubusercontent.com/3190416/149615709-eedee908-801c-4aac-9cb0-f7f3b53ba917.png)

Anyone knows how to address it?

**Comment by packagethief** [comment]
This is working as intended. The `turbo-visit-control=reload` directive tells Turbo to reload the page after navigating to it. It's similar to what happens when Turbo [detects that tracked assets have changed](https://turbo.hotwired.dev/handbook/drive#reloading-when-assets-change) after navigation. With `turbo-visit-control` you're telling it to always do that.

It's really meant for specific Turbo-resistant pages, not to be used site-wide. Doing so would defeat the purpose 😄

**Comment by ChrisZou** [comment]
@packagethief Thanks for the reply. I now understand. The goal I wanted to achieve is to disable turbo drive only and still keep using turbo frame and turbo stream. Is there any way I can do that? I tried `Turbo.session.drive = false`, but this will also disable turbo frame and turbo stream.
