### ISSUE TITLE
None of the Turbo events are not triggered on 422

### ISSUE THREAD

**Issue by james-em** [hotwired/turbo#520]
Hi,

Kind of reopening https://github.com/hotwired/turbo/issues/85

When you have form errors and render it using turbo streams

```
# Ruby
render :edit, status: :unprocessable_entity

# JS
document.addEventListener('turbo:load', () => queryDocumentForTomSelect());
document.addEventListener('turbo:render', () => queryDocumentForTomSelect());
document.addEventListener('turbo:before-render', () => queryDocumentForTomSelect());
document.addEventListener('turbo:frame-load', () => queryDocumentForTomSelect());
```

None of the Javascript events are triggered making impossible to load libraries such as Tom-Select or Bootstrap custom calendars.

Some people recommends to add data-controller attribute and use stimulus controller, but none of them show how to properly do it when you have **many** input you want to trigger or that maybe you already call **another controller on the same input**.

What are the proper workaround ?

Thank you

**Comment by seanpdoyle** [comment]
Would listening for a [turbo:before-stream-render](https://turbo.hotwired.dev/reference/events) event suit your use case?

**Comment by seanpdoyle** [comment]
> Some people recommends to add data-controller attribute and use stimulus controller, but none of them show how to properly do it when you have many input you want to trigger or that maybe you already call another controller on the same input.

If you're on Stimulus v3, you have access to [target connection callbacks](https://stimulus.hotwired.dev/reference/targets#connected-and-disconnected-callbacks), which could help you avoid event listening entirely.

If your Stimulus controller is high-enough in the page's hierarchy, you could annotate elements with `[data-$IDENTIFIER-target~="tomSelect"]`, then declare a `tomSelectTargetConnected(target)` callback and `tomSelectTargetDisconnected(target)` to manage installing and uninstalling whatever plugin you're using.

This avoids event listeners, page visits vs. Turbo Streams, etc because Stimulus manages the plugin entirely based on whether or not the element is present or absent in the document.

**Comment by james-em** [comment]
@seanpdoyle 

Thanks for your reply. It's very appreciated !

The event turbo:before-stream-render is indeed called but loading plugins from there doesn't work. Probably if I use a setTimeout(() => { ... }, 1000) that would work but I find it ugly.

I went ahead and gave a try to your method:

```
import {Controller} from "@hotwired/stimulus"
import {loadTomSelect} from "../libs/tom-select";

// Connects to data-controller="tomselect"
export default class extends Controller {
  static targets = ["ts"]

  tsTargetConnected(selectInput) {
    if (selectInput.classList.contains('tomselected')) return;
    if (selectInput.classList.contains('no-ts')) return;

    if (selectInput.classList.contains('tomselect-ajax')) {
      loadTomSelect(selectInput, true);
    } else {
      loadTomSelect(selectInput, false);
    }
  }
}
```

Append to all my select `input: , data: { "tomselect-target": "inputs" }` and it does indeed work flawlessly. 

I would be happy with this solution, but there is one thing that bothers me and is doing this to my body (It's HAML)

```
%body{data: { controller: 'tomselect' }}
```
If I have multiple libraries that would get ugly, I would then need to do this:

```
<body data-controller="library1">
 <div data-controller="library2">
    <div data-controller="library3">
      content...
    </div>
</div>
</body>
```

Isn't there a better way?

**Comment by seanpdoyle** [comment]
The data- attributes that power Stimulus accept token lists, so you can add controller identifiers or action descriptors as lists separated by spaces.

**Comment by james-em** [comment]
> The data- attributes that power Stimulus accept token lists, so you can add controller identifiers or action descriptors as lists separated by spaces.

You mean that

```
<body data-controller="library1 library2 library3">
```

would be valid?

**Comment by seanpdoyle** [comment]
That's right! The same is true for `data-action="click->library1#doSomething click->library2#doSomethingElse"`.

**Comment by james-em** [comment]
> That's right! The same is true for `data-action="click->library1#doSomething click->library2#doSomethingElse"`.

Thank you I didn't know! Thanks for all the quick replies. Very appreciated. I'm closing the issue

**Comment by jdsampayo** [comment]
The solution of `TargetConnected / TargetDisconnected` is great because it works with any plugin (tomselect, flatpickr, etc). Basically the ones that use `addEventListener("turbo:load")` can be written like that.

Particularly for tom-select, I found this wrapper that works great:
https://github.com/bbonamin/stimulus-tom-select

**Comment by defsdoor** [comment]
I'm in the middle of migrating a massive old code base and am looking for a simple solution to this so that I can re-implement the existing javascript at my leisure.

My approach is to simply have a stimulus controller on body (on all layouts) that fires a new Event -

```javascript
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  connect() {
    document.dispatchEvent(new Event("document:page_loaded"));
  }
}
```

and instead of replacing all the document:ready and turbolinks:load events with turbo:load, replace them with -

```javascript
  $(document).on("document:page_loaded", function () { .... }
  ```
  
  
  However I'm nervous that this is extremely naive and that I might be missing something obvious.
  
  Am I ?
