### ISSUE TITLE
Opt-in Turbo Drive breaks data-turbo-confirm messages

### ISSUE THREAD

**Issue by alexandergitter** [hotwired/turbo#538]
According to the Turbo Handbook (https://turbo.hotwired.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms) it's possible to make Drive opt-in by setting `Turbo.session.drive = false` and then enabling Turbo on a per-element basis setting `data-turbo="true"`.

This however seems to break the confirm alerts that can be added with `data-turbo-confirm="Confirm"`.

Here's a small example to test this: 
(live at https://jsfiddle.net/xrc2zp5y)
```javascript
import * as Turbo from "https://cdn.skypack.dev/@hotwired/turbo"
Turbo.session.drive = false
```

```html
<a href="#" data-turbo="true" data-turbo-method="post" data-turbo-confirm="Confirm">Click me</a>
```

**Comment by tchak** [comment]
`data-turbo="true"` will not work on a link itself. You have to put it on a parent element. You will still have a problem with `data-turbo-method=“post”` because in order to "submit" the link turbo will create a form element and attach it to the `<body>` and then try to dispatch a `submit` event on it, but since turbo is globally disabled it will not work.
