### ISSUE TITLE
Back link with scroll position restore

### ISSUE THREAD

**Issue by timrosskamp** [hotwired/turbo#549]
I'd like to have a link `<a>` on my page that links to the previous page. But the scroll position won't be restored unless the browser back button is used. Is there a way to "opt-in" into scroll position restoration on a link?

**Comment by jacobdaddario** [comment]
Scroll position with Turbo seems to be a hot topic. This is mentioned all the way back in #37. I think development on features has been stalled for the time being, or at least as far as anyone has heard. With that said, I don't believe that there's a method of maintaining scroll position on drive requests as of right now. If you have ideas or are looking for workarounds, I think #37 might be the best place to look.

Regardless, as of now I think that this issue is probably safe to close cc: @dhh.

**Comment by dhh** [comment]
We absolutely have issues with scroll position. Hope to kick off a larger inquiry into this as we need to fix it for HEY as well. But right now there's no such affordance.
