### ISSUE TITLE
Double click protection with data-disable

### ISSUE THREAD

**Issue by mrhead** [hotwired/turbo#55]
First thing first: Thank you for sharing Hotwire! I like it a lot.

Turbo partly replaces rails-ujs. This makes sense. However, together with other functionality we lose double click protection which was implemented in rails-ujs with `data-disable` and `data-disable-with`.

Are there any plans or appetite for adding this directly to Turbo? Or do you suggest to handle this with a Stimulus controller instead?

I would kind of like to see this implemented directly in Turbo so this work for people out of box like it worked with rails-ujs which is installed in Rails by default. On the other hand I would understand if there is no appetite for adding this.

**Comment by dhh** [comment]
We've stopped recommending removing UJS altogether. See https://github.com/hotwired/turbo-rails/commit/9d53529bedd4de19dea8521d415f40685dfe7749 👍

**Comment by coorasse** [comment]
I just noticed a bug regarding `data-disable-with`.

If I disable the submit button of a form with GET method, and the result is fetched from the cache, the button stays with the disabled text since it was cached like that. 
Disabling the cache solves the issue of course.

![image](https://user-images.githubusercontent.com/1319150/103371404-a44b0e00-4acf-11eb-9130-16016df682a7.png)

**Comment by mrhead** [comment]
@dhh The issue with rails-ujs is that it doesn't listen to Turbo events. So if you use turbo streams to update page content and don't replace the original Turbo frame, then the button which was previously disabled is not enabled again after a Turbo request finishes.

I see two options for improving this:

1. Add this directly to Turbo.
2. Create a new super simple UJS adapter (e.g. turbo-ujs).

Do you see any possibility of adding `data-confirm` directly to Turbo? If not, then the second option is probably a way to go.

**Comment by ghiculescu** [comment]
If turbo could dispatch `ajax:complete` in addition to its [other events](https://turbo.hotwire.dev/reference/events), I think that would make life a lo simpler. A common issue we've come across while upgrading from Turbolinks is this pattern.

- User submits a form.
- Form submit button is disabled (thanks to `data-disabled-with` built in to Rails / UJs).
- Form has an error that server side validation finds. Previously we'd render `create.js.erb` which would do something to display the error message. Now we can do the same thing using a turbo stream.
- But because `ajax:complete` never fires, the form submit button remains disabled now.

**Comment by ghiculescu** [comment]
I had a similar issue to @mrhead, and ended up using a stimulus controller based on the one in the hotwired demo.

Controller from the demo: https://github.com/hotwired/hotwire-rails-demo-chat/blob/main/app/assets/javascripts/controllers/reset_form_controller.js

How it's used: https://github.com/hotwired/hotwire-rails-demo-chat/blob/main/app/views/messages/new.html.erb#L5

My full controller ended up looking like this:

```js
import { Controller } from "stimulus"

export default class extends Controller {
  reset() {
    this.element.reset()  // reset form contents
    this.element.querySelectorAll("input[type=submit]").forEach(button => button.disabled = false) // reset data-disable-with
  }
}
```

**Comment by oliwoodsuk** [comment]
Here's one for links:
```javascript
//click_controller.js

import { Controller } from "stimulus"

export default class extends Controller {
	
	butNotTwice() {
		let linkHref = this.element.href
		
		setTimeout(() => {
			this.disableLink()
			this.waitThenReEnable(linkHref)
		}, 50)
	}

	
	//private
	
	disableLink(){
		this.element.href = "javascript:void(0)"
	}
	
	waitThenReEnable(linkHref){
		setTimeout(() => {
			if (this.element) this.element.href = linkHref;
		}, 3000)
	}

}
```

Then in erb:
```HTML+ERB
<%= link_to( " A great product", "products/#{product.id}", data: {controller: "click", action: "click#butNotTwice"})
```

**Comment by Aiderlei** [comment]
The cleanest way is to hook register event listeners of the turbo submit event:

```js
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  connect() {
    this.element.addEventListener("turbo:submit-start", this.toggleDisabledOnFields)
  }

  disconnect() {
    this.element.removeEventListener("turbo:submit-start", this.toggleDisabledOnFields)
  }

  toggleDisabledOnFields({ target }) {
    for (const field of target.elements) field.disabled = !field.disabled
  }
}
```

And then set `data: { controller: "disable" }` on your form.
