### ISSUE TITLE
GA4 not compatible with Turbo?

### ISSUE THREAD

**Issue by noctivityinc** [hotwired/turbo#572]
I have a weird one.  Everything was working fine until I installed Google Analytics 4 (GA4).  Once I installed it, my turbo frame links are being followed instead of doing what they are suppose to do and just loading the response data.

Is anyone else having this issue and how did you solve it?

**Comment by noctivityinc** [comment]
It seems to be related to GA4 automatically tracking outbound clicks.  When you shut that off it seems to work.

**Comment by t27duck** [comment]
A couple random Stackoverflow posts also imply that if GA4 is implemented with google tag manager (gtm js), things should still work, but I haven't confirmed this personally.

**Comment by t27duck** [comment]
I think it just "works". Again, haven't confirmed.

I have a UA site using gtm I was going to look into converting "soon" (since we have a year before UA goes away) and will give it a shot.

That said, at least there's an out for now with during off outbound clicks...

**Comment by rogerkk** [comment]
Enhanced Measurement in GA4 is not enabled by default, I think, which perhaps could explain why some people will see it just working.

**Comment by jakemumu** [comment]
grateful to have found this thank you!

**Comment by svobom57** [comment]
I'm still experiencing this issue from the looks of it even today... Having the GTM tag in the `<head>` breaks the Turbo link visits and instead forces full page reload.

**Comment by JYorston** [comment]
We are also experiencing this, we've disabled the "Enhanced measurement" feature in Google Analytics per the SO post above, and that has resolved it for now.  

Interestingly we had this issue before, and like other commenters, it then "just worked" for a while and now it's back.

**Comment by Fodoj** [comment]
Same issue appears if you happen to use CloudFlare - it has a feature called Rocket Loader (https://developers.cloudflare.com/speed/optimization/content/rocket-loader/), which breaks Turbo in the same way (and it also adds new event listener for every link). Disabling the feature in CloudFlare fixed the problem.

**Comment by calleluks** [comment]
I just integrated GA4 tracking in a Rails 7.1 app that uses Turbo Drive with a property that has "Enhanced Measurement" enabled by literally pasting the gtag.js code snippet just after `<head>` and and everything seems to be working.

Are you still seeing issues on the latest version of Turbo?

**Comment by pokonski** [comment]
No issues for me with default GA4 config and Turbo. No hard reloads.

**Comment by dhh** [comment]
If anyone wants to document these compatibility issues in the turbo-site repo, I'd be happy to merge 👍

**Comment by tbcooney** [comment]
For those that were able to integrated GA4 tracking with Turbo Drive, how did you get it to work?

Because Turbo Drive relies on using a [single, persistent process](https://turbo.hotwired.dev/handbook/introduction#turbo-drive%3A-navigate-within-a-persistent-process) when navigating pages, the `<script>` element is only executed a single time. My experience when `Turbo.Visit` is driving the page click causes GA not to track the additional page views. I can confirm this when I check the network tab in developer tools after any page click, I don't see any requests that contain `/collect?v=2`. I can quickly find GA requests for the initial page load.

So far the only thing so far that has worked is to add `data: { turbo: false }` to the `link_to` helper that handles the page click.

**Comment by calleluks** [comment]
I think the key to making it work when just including the script tag is to make sure ["Enhanced Measurement"](https://support.google.com/analytics/answer/9216061) is enabled for the property. Then GA4 seems to automatically track pageview events based on the browser history events generated by Turbo Drive.

**Comment by t27duck** [comment]
@tbcooney See the answer in the linked stackoverflow here as a starting point: https://github.com/hotwired/turbo/issues/572#issuecomment-1113339922

or alternatively, use the `turbo:load` event in place of the turbolinks variant as outlined here: https://gorails.com/episodes/gtag-js-with-turbolinks

**Comment by tbcooney** [comment]
Thanks @t27duck. Unfortunately, that is the _exact script_ that is in place.

I've created [this staging website](https://www.myporridgestorage.com/) to demonstrate the issue I'm facing. When I check the network tab in developer tools after any page click, I don't see any requests that contain `/collect?v=2`. I can quickly find GA requests for the initial page load.

For context, this is the same behaviour whether Enhanced Measurement is turned off or Enhanced Measurement is turned on with browser history-based events turned off -- any subsequent page view is not tracked.
<img width="848" alt="Screenshot 2024-05-17 at 8 37 29 AM" src="https://github.com/hotwired/turbo/assets/10053844/f70dc1f7-29cb-474f-8e4f-f9aa420c0214">

So far the only thing so far that has worked is to add `data: { turbo: false }` to the `link_to` helper that handles the page click. That seems like a less than ideal solution as it requires developers to have quite an intimate understanding of the application and it's relationship with GA to follow this in practice when adding any new links in the future.

**Comment by borama** [comment]
We also hit this issue while having GA4 served via GTM and after switching the Enhanced measurement in GA4 on.

We resolved the issue by disabling Enhanced measurement altogether but we noticed that enabling it and specifically disabling Outbound clicks + File downloads tracking worked for us too.

![2024-07-26_12-00](https://github.com/user-attachments/assets/67a6bb21-53da-474f-b8a6-3f86d0894950)

**Comment by rafaeldev** [comment]
GTM Form Submission trigger (not just GA4 links) can silently bypass Turbo — including turbo_confirm
Adding to this thread, since most of it focuses on links / GA4 Enhanced Measurement. We hit a more dangerous variant on the form side.
If your GTM container has a Form Submission trigger with "Wait for Tags" and/or "Check Validation" enabled (especially one scoped to All Forms), GTM installs a capture-phase submit listener that calls `event.preventDefault()` and re-submits the form via the native `HTMLFormElement.submit()`. The native call doesn't dispatch a submit event, so Turbo never sees it — which means:

- Turbo Drive form handling is bypassed (full navigation instead of in-place).
- `Turbo.config.forms.confirm` / `data-turbo-confirm` is skipped entirely, so destructive button_to method: :delete actions execute without the confirmation dialog.
- `link_to data: { turbo_method: :delete }` ends up as a GET → 404 (browsers don't support `<form method=delete>`).

Fix that worked for us: in the GTM Form Submission trigger, uncheck "Wait for Tags" and "Check Validation". Without those, GTM listens passively (no preventDefault) and Turbo behaves normally. GTM itself warns these options are "very invasive on single-page apps."
