### ISSUE TITLE
Eager loading frame not loading src content on second visit

### ISSUE THREAD

**Issue by colinmathews** [hotwired/turbo#581]
### Conditions
This only seems to be an issue when the server is serving plain text/html content (it works if Turbo streams are sent back). Here is a [demo of the issue](https://replit.com/@colingmathews/turbo-issues?v=1) (after starting the replit, click "Eager loading test").

### Description of issue
I have a frame using eager loading to show a loading message and then show the actual content:

```
<turbo-frame id="target-frame" src="./initial.html">
  Loading...
</turbo-frame>
```

`initial.html` delivers this:

```
<turbo-frame id="target-frame">
  <p>
    This is the loaded content!
  </p>
  <a href="./secondary.html">
    To secondary page
  </a>
</turbo-frame>
```

When you click "To secondary page" it works as expected and you get this:

```
<turbo-frame id="target-frame">
  <a href="./index.html">
    Back to first page
  </a>
</turbo-frame>
```

Clicking this link sends you back to the first page, but it gets stuck at the loading view (even though the network requests show it fetches the initial.html content). 

### Discussion

[I opened a thread](https://discuss.hotwired.dev/t/eager-loading-frame-not-loading-src-content-on-second-visit/4108) and a commenter suggested that this is a bug:

> This appears a bug. The software renders something like:
> 
> - fetch index.html
>   - create index snapshot
>     - fetch initial.html
>       - create initial snapshot
>       - render initial snapshot
>   - render index snapshot
> 
> Where the snapshot at the end contains the original index snapshot, not the index + initial snapshot.

**Comment by extendednotes** [comment]
I've had exactly the same problem. What happens if you break out of the frame with **data-turbo-frame="_top"**?
So in your case this should do the trick:

```
<turbo-frame id="target-frame">
  <a href="./index.html" data-turbo-frame="_top">
    Back to first page
  </a>
</turbo-frame>
```

**Comment by mattbrictson** [comment]
First time using Turbo Frames with the `src` attribute and I am running into the same problem as well.

I can see the request being made in the browser dev tools and the HTML coming back, but Turbo never updates the frame.

@colinmathews did you find another workaround?

**Comment by colinmathews** [comment]
Hey @mattbrictson - the workaround is that the server must send back HTML with the content-type: `text/vnd.turbo-stream.html`

When that's in place it all works. The issue here is that if you have a static web server this isn't possible.

**Comment by brunoprietog** [comment]
The src attribute of a Turbo frame represents the current URL of the last visit of a Turbo frame. If you change it manually, for example using the element's src property, it will result in a visit in that Turbo frame to the provided URL. If a Turbo frame, on initial load, has a src attribute, it will render the content found inside the Turbo frame, while Turbo proposes a visit to the URL found in the Turbo frame's src attribute. Then, it will replace that content with the new content coming from the server response, which is the content inside the Turbo frame with the same ID that comes in that response. If you click on a link, Turbo will change the src attribute of the Turbo frame and set it to the URL of the link you just clicked. Then, it will propose another visit, following the same process described above, that is, it will search the response coming from the server for a Turbo frame with the same ID and replace the current content with the new content coming inside that Turbo frame. At no time will it take into account the src attribute of the Turbo frame that comes in the response, it only replaces the internal content. The src attribute should be used only to indicate the initial loading of a Turbo frame, but should not be included in the following responses, because it will have no effect.

In your case, what you want is not to return to the initial page. What you want is to return to the URL that should represent the Turbo frame after its initial loading.

Path: "/index.html"

```html
<turbo-frame id="target-frame" src="./initial.html">
  Loading...
</turbo-frame>
```

Path: "/initial.html"

```html
<turbo-frame id="target-frame">
  <p>
    This is the loaded content!
  </p>
  <a href="./secondary.html">
    To secondary page
  </a>
</turbo-frame>
```

Path: "/secondary.html"

```html
<turbo-frame id="target-frame">
  <a href="./initial.html">
    Back to first page
  </a>
</turbo-frame>
```

Note the change in the last Turbo frame. What you want is to re-render the Turbo frame content from "initial.html", not from "index.html". The content of the Turbo frame from "index.html" is just temporary, while Turbo loads the content that the Turbo frame should actually have after the initial load.

Hope this helps

**Comment by colinmathews** [comment]
Thank you @brunoprietog! That does make sense. The behavior I was looking for _does_ work when turbo streams are sent back from the server, just not when text/html is the response type, so that is curious.

One problem with what you're suggesting is that if we are using `data-turbo-action="advance"` so that clicking these links changes the url, the "Back to the first page" link _must_ use `index.html` because that's the actual page we want the user to go to.

**Comment by brunoprietog** [comment]
Why do you want to mix Turbo streams with Turbo frames in the same request?

> One problem with what you're suggesting is that if we are using data-turbo-action="advance" so that clicking these links changes the url, the "Back to the first page" link must use index.html because that's the actual page we want the user to go to.

That's a good point. In that case, I think ideally you should try not to eager load the Turbo frame.
