### ISSUE TITLE
jquery datepicker stop work after hit browser back

### ISSUE THREAD

**Issue by williamherry** [hotwired/turbo#646]
When I successfully attach a jQuery picker to an element, navigate to another page, and click the browser back button, the handler is no longer attached and the date picker does not appear, even if I manually attach again. no error message in console.

![568113b2-1096-11e7-833d-e8d383776930](https://user-images.githubusercontent.com/1032483/180608565-70f10f63-dde7-4ddf-b4f1-aefe64fddba1.gif)

If I navigate back to the page by clicking, say a 'Back' link, it works properly.

there is a similar issue created under turbolinks repo [jQuery handler (datepicker) removed after hitting back button on Turbolinks ](https://github.com/turbolinks/turbolinks/issues/311), the fix provided in comment do not work with new turbo and hotwire staff, I guess the event name has been changed.

```
document.addEventListener "turbolinks:before-cache", ->
  $.datepicker.dpDiv.remove()

  for element in document.querySelectorAll("input.hasDatepicker")
    $(element).datepicker("destroy")

document.addEventListener "turbolinks:before-render", (event) ->
  $.datepicker.dpDiv.appendTo(event.data.newBody)
```

Thanks

**Comment by marcoroth** [comment]
Hey @williamherry, are you running Turbo now? If so, you could try the same approach with the new event name `turbo:before-cache`. 

For the long-term: it would probably be better if you replace the jQuery dependency and migrate this behavior to a Stimulus controller which is designed to work with the Turbo lifecycle. It's a lot easier execute the right JavaScript code in the right moment, because you can react to it every time the element is connected/disconnected, instead of whenever you navigate back/forward.

**Comment by williamherry** [comment]
Thanks @marcoroth, I tried `turbo:before-cache` / `turbo:before-render`, still not work, finally I switch to use another plugin, which works perfectly and looks more pretty, https://flatpickr.js.org/, will lose this.
