### ISSUE TITLE
Forms with non GET, POST methods

### ISSUE THREAD

**Issue by tothda** [hotwired/turbo#69]
Due to the change in #1, there is no way to set a `form`'s method to `PUT` or `DELETE`. It is however possible with the `formmethod` attribute of the `submitter` element.

Relevant code from `form_submissions.ts`:

```
  get method(): FetchMethod {
    const method = this.submitter?.getAttribute("formmethod") || this.formElement.method
    return fetchMethodFromString(method.toLowerCase()) || FetchMethod.get
  }
```

The reason is visible on the following screenshot. Meanwhile `getAttribute("formmethod")` returns the string from the HTML, `this.formElement.method` returns `"get"` with not respect to the value `"delete"` in the HTML. I guess because it is not a valid value according to the spec (and yeah, `"delete"` is not a valid value for `formmethod` either.)

![image](https://user-images.githubusercontent.com/7077/103484162-eedccb00-4dec-11eb-9d42-668403e1c328.png)

What is the best practice with respect to non `GET` and `POST` requests?

Thanks!

**Comment by javan** [comment]
Caused by bf257f3c40e9566955ad8a7329060a9e276fd429's change from `formElement.getAttribute("method")` to `formElement.method`:
```diff
   get method(): FetchMethod {
-    const method = this.formElement.getAttribute("method") || ""
+    const method = this.submitter?.getAttribute("formmethod") || this.formElement.method
     return fetchMethodFromString(method.toLowerCase()) || FetchMethod.get
   }
```
/cc @seanpdoyle

**Comment by seanpdoyle** [comment]
It didn't occur to me before, but did Turbo support `<form method="delete">`? Anything other than `GET` or `POST` is not supported by browser form submissions. The change to use [HTMLFormElement.method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/method) was made with the intention of leaning on the browser defaults. 

Rails works around the constraint by encoding the method via an `<input type="hidden" name="_method" value="...">`.

After a quick search through the codebase, the only references to `FetchRequest.method` seem to involve either `FetchMethod.get` or `!= FetchMethod.get`:

* [src/core/drive/form_submission.ts](https://github.com/hotwired/turbo/blob/ea00632e9790a680c7704d90101403f34d9433a6/src/core/drive/form_submission.ts#L82-L87)
* [src/core/frames/frame_controller.ts](https://github.com/hotwired/turbo/blob/4227383d91ace6fb1dd88b3c3f8c4e9660de0430/src/core/frames/frame_controller.ts#L60)
* [src/core/drive/navigator.ts](https://github.com/hotwired/turbo/blob/18b755f6210a270ad6d9eedaf1195a474e82d9cb/src/core/drive/navigator.ts#L78)

Since Turbo works hand-in-glove with Rails, I hadn't considered expanding support for other HTTP verbs as an attribute. From a progressive enhancement perspective, that feels riskier than a Rails-style server-side workaround.

@tothda had you considered a Rails-like server side workaround for forms with `PUT` or `DELETE`?

> Meanwhile `getAttribute("formmethod")` returns the string from the HTML

@javan should we limit the value we read from `formmethod` to `FetchMethod.{get,post}`?

**Comment by javan** [comment]
I think we should restore the previous behavior for now even if it's non standard.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/75 to revert that part of bf257f3.

**Comment by tothda** [comment]
@seanpdoyle Yes, I considered using `_method` but I'm not using rails, so I'd have had to add support for it. It seemed more convenient to make the browser issue a real DELETE request. But giving it more thought it is probably better to stick to the HTML standard, because without javascript the browser would still send a GET even if we have `DELETE` in the markup, and then the app would break.
