### ISSUE TITLE
Why is <template> tag necessery?

### ISSUE THREAD

**Issue by swistak** [hotwired/turbo#803]
Hello. I googled but didn't find an answer to this. Documentation states that `<template>` tag is required inside `<turbo-stream>` tag, but is there actual reason for this or is it just an implementation detail?

**Comment by marcoroth** [comment]
Hey @swistak, the `<template>` tag inside `<turbo-stream>`'s is not required anymore if the action doesn't require it. I'd assume that the documentation is outdated then. For context: https://github.com/hotwired/turbo/pull/665

Feel free to open a documentation PR to or show us where it is so we can update it. Thank you!

**Comment by swistak** [comment]
Thanks @marcoroth I found that mention in https://turbo.hotwired.dev/handbook/streams

> Note that every `<turbo-stream>` element must wrap its included HTML inside a `<template>` element.

But what I was wondering why that element must exist in the first place? `<turbo-frame>`s don't require template inside, I was wondering why is that seemingly superficial element there in the first place?

**Comment by marcoroth** [comment]
I see two reasons for that, 1) since a `<turbo-stream>` is a regular HTML custom element it would show its content by default unless you would hide it via CSS somehow. On the other hand, the content of `<template>` tags is not shown by default.
2) The `<template>` tag acts as a good container, its content is being parsed and handled as regular HTML, just not shown. It also offers a few functions on the element itself to work with the content, like cloning it.

I'm sure you could also implement Turbo Streams without template tags and having these gotchas in mind, but in this case they turn out to be useful.
