### ISSUE TITLE
Stimulus Binds Twice on New Page after Redirect to GET Request

### ISSUE THREAD

**Issue by rience** [hotwired/turbo#828]
Hi,

I've observed this strange behaviour and I couldn't find information about that in documentation. Stimulus does connect, disconnect and connect again page user is redirected to - depends on what was method used in previous request.

Test scenario

1. Have controller's action that responds with redirect to new page (the one with Stimulus controller).
2. Bind this action to GET request - observe in console that Stimulus will connect, disconnect and connect again.
3. Now change this action to POST - observe that Stimulus will only connect once.

This is in Rails 7 application with Turbo framework. However, I've opted-out of caching there.

You can find application that demonstrates this behaviour here: https://github.com/rience/stimulus-double-bind

Thank you in advance for help.

P.S. Originally it was created in Stimulus repo but this probably is Turbo issue: https://github.com/hotwired/stimulus/issues/629

**Comment by marcoroth** [comment]
Hey @rience, I was able to narrow down why your Stimulus controller is connect twice.

The reason is your first GET request is redirecting from `/test/new` to `/test/show`:

```
23:07:31 web.1  | Started GET "/test/new" for ::1 at 2022-12-23 23:07:31 +0100
23:07:31 web.1  | Processing by TestController#new as HTML
23:07:31 web.1  | Redirected to http://localhost:3000/test/show
23:07:31 web.1  | Completed 302 Found in 1ms (Allocations: 125)
23:07:31 web.1  |
23:07:31 web.1  |
23:07:31 web.1  | Started GET "/test/show" for ::1 at 2022-12-23 23:07:31 +0100
23:07:31 web.1  | Processing by TestController#show as HTML
23:07:31 web.1  |   Rendering layout layouts/application.html.erb
23:07:31 web.1  |   Rendering test/show.html.erb within layouts/application
23:07:31 web.1  |   Rendered test/show.html.erb within layouts/application (Duration: 0.0ms | Allocations: 11)
23:07:31 web.1  |   Rendered layout layouts/application.html.erb (Duration: 2.9ms | Allocations: 1980)
23:07:31 web.1  | Completed 200 OK in 4ms (Views: 3.3ms | Allocations: 2215)
```

If you change your markup it works as expected:
```html
<!-- app/views/home/show.html.erb -->

<h1>Home#show</h1>
<%= link_to "Test GET", "/test/show" %>
<%= link_to "Test POST", test_create_path, data: { turbo_method: :post } %>
```

But the question remains: should the Stimulus controller be connected twice in this case, or in Turbo terminology, should the body be updated/replaced twice if the request returned a 302. 

Turbo is calling `BrowserAdapter.visitProposedToLocation()` twice in this case. At the end of the first call it ??`this.followRedirect()` which causes the second visit and connect here:

https://github.com/hotwired/turbo/blob/b8ecc46d93816195898e655ebb9d3337abc98cce/src/core/drive/visit.ts#L186-L196

I tried to visualize the sequence here:

![Screenshot 2022-12-23 at 23 29 31](https://user-images.githubusercontent.com/6411752/209410560-2c270ace-3abb-4120-97b5-92b302056930.png)

**Comment by marcoroth** [comment]
I just realized this might be a duplicate of https://github.com/hotwired/turbo/issues/794 which might be fixed by @seanpdoyle's PR: https://github.com/hotwired/turbo/pull/804

**Comment by rience** [comment]
Hi @marcoroth,

Sorry for delay in my response. Many thanks for looking into this and preparing such clear explanation. I'll observe the other ticket then.
