### ISSUE TITLE
Attribute class is ignored when loading frame

### ISSUE THREAD

**Issue by benzen** [hotwired/turbo#830]
If i have a turbo frame declared like this in my main page
```
<div class="parentElement">
  <turbo-frame 
                  th:src="@{/someUrl}" 
                  id="some-id"/>
</div>
```

When this frame is loaded, if my description of this frame looks like this

```
<turbo-frame id="some-id class="some-nice-looking-class">
....
</turbo-frame>
```

Even if everything is correctly wired with my backend, the class `some-nice-looking-class` will not be applied in my main page.

Depending on you system on class, this could be a non issue, since you can always put the same class on element below.
But some css style system require a direct link between element with certain classes.

I assume that all attribute will exibit the same behavior, but I did'nt test that assumption.

I think the good thing to do is to merge previously set attributes with the new attributes .

**Comment by seanpdoyle** [comment]
Frame elements are currently rendered with the same "action" as a [`<turbo-stream action="update">`](https://turbo.hotwired.dev/reference/streams#update) element. The underlying renderer extracts the contents of the incoming frame and uses them to replace the current frame's contents. The `<turbo-frame>` element itself remains unchanged, saved for its `[src]`, `[busy]`, and `[complete]` attributes expose the state of the the navigation or form submission lifecycle.

The concept of a different rendering style was explored in https://github.com/hotwired/turbo/pull/146. For example, to achieve the behavior you're describing, you're render the new frame with [action="replace"](https://turbo.hotwired.dev/reference/streams#replace) semantics instead of [action="update"](https://turbo.hotwired.dev/reference/streams#update) semantics.

**Comment by benzen** [comment]
thanks for the link, very interesting to follow the tought process on this.

The way in thought about it is the same as turbo loading a complete page. 
When navigating from one page to the next, headers are merged between the previous page and the next. And the content is "replaced".

I imagined turbo would have done the same with the element turbo-frame attributes and it's content.

**Comment by seanpdoyle** [comment]
I've tried to document this behavior in https://github.com/hotwired/turbo-site/commit/4231925372b206b6d34e1657bcbdb2a0c34c29b0#diff-94c46ee78d634c0e9a59142bdab9b15fd453f00c7d8096cfa16f32271b25f1e2R224.

**Comment by benzen** [comment]
I think this would be a great addition to the doc.
