### ISSUE TITLE
turbo:load won't be triggered when a FormSubmission request fails

### ISSUE THREAD

**Issue by nyrf** [hotwired/turbo#85]
When a FormSubmission request fails and return 400-500 code, `turbo:load` won't be triggered. eg:

`application.js`

```js
document.addEventListener('turbo:load', function () {
  console.log('turbo load')
  document.getElementById('demo').replaceWith('demo replace')
})

```

`new.html.erb`

```
<div id="demo">demo</div>
<%= form_with(model: @post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>
```

`posts_controller.rb`

```ruby
def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

```ruby
class Post < ApplicationRecord
  validates :title, presence: true
end
```

After submit form, it should show `demo replace`, but it showed `demo` because of `turbo:load` hasn't be triggered.

![error2](https://user-images.githubusercontent.com/299532/103898975-a9900480-5130-11eb-9327-93d1129afd20.gif)

More info https://github.com/SimoTod/alpine-turbo-drive-adapter/issues/29#issuecomment-756062646

**Comment by sstephenson** [comment]
This is by design. The `turbo:load` event fires in response to a successful visit, and form submissions only trigger visits when the server responds with a redirect.

**Comment by nyrf** [comment]
So, the PR https://github.com/hotwired/turbo/pull/39  is useless?  We often use `turbo:load` event to run some codes, if this is by design, after submit form fail and return 422, the code inside `turbo:load` won't run. So, how to run the codes inside `turbo:load`?

**Comment by sstephenson** [comment]
You shouldn't listen for the `turbo:load` event unless you specifically want to know that a visit—a navigation that changes the URL—has finished. 

The Hotwire way is to put the code you want to run in the `connect()` method of a Stimulus controller, and then add a matching `data-controller` attribute to an element so that the code runs whenever the element appears on the page.

**Comment by nyrf** [comment]
> The Hotwire way is to put the code you want to run in the `connect()` method of a Stimulus controller, and then add a matching `data-controller` attribute to an element so that the code runs whenever the element appears on the page.

I see, thanks.

**Comment by SimoTod** [comment]
@sstephenson Silly question, the page does get replaced though (it rerender the old page triggering a turbo:render event).
If the goal is to keep the page as it is, why does it replace the content? Thanks

**Comment by florentdestremau** [comment]
I find the decision not to fire the `turbo:load` event not in line with the docs:

> Turbo Drive evaluates <script> elements in a page’s <body> each time it renders the page. You can use inline body scripts to set up per-page JavaScript state or bootstrap client-side models. To install behavior, or to perform more complex operations when the page changes, avoid script elements and **use the turbo:load event instead**.

So that means that if my form has some JS in it (ex. booting a bootstrap-datepicker with jquery, launching a google autocomplete...), the JS is not re-initialized but the the DOM has changed. 

I ended up using `turbo:render` instead to boot my custom JS (I'm migrating my current app to turbo, so a lot of custom JS hanging around). I don't see why the docs would point me to `turbo:load` then if `turbo:render` is the more universal event ? Am I missing something ?

**Comment by rossinkiwi** [comment]
Ouch! This means that all of our existing legacy code that once was based on:
`$(document).ready( function( e ) { ... code to init legacy js like parsley, datatables, datetimepicker etc. ...}`
Then replaced with:
`$(document).on('turbolinks:load', function( e ) { ... legacy js code ...}`
Then replaced with:
`$(document).on('turbo:load', function( e ) { ... legacy js code ...}`
Now won't work in the case of a form submission that has validation errors?

And all of that has to be migrated to Stimulus?
Is there no way around this?  I tried to use the `turbo:render` event and it too does not get triggered when a form submission fails.

**Comment by florentdestremau** [comment]
I ended up booting 3 times: `turbo:render`, `turbo:load` and `load`.

Because React seems to be idempotent, and our codebase seems to be as well, we haven't noticed a major memory leak or slowness. Still, this is upsetting because it's not advertised as such.

What I understand is that only stimulus code is automatically re-booted if necessary, but external dependencies are to be either idempotent and booted multiple times, or booted once and hope for no re-render @sstephenson ?

**Comment by buncis** [comment]
I also have a react component that I attached using `turbo:load`
my current solution is 

adding document listerner for `turbo:load` and `turbo:render`
```
  document.addEventListener('turbo:load', () => {
    let domContainer = document.querySelector('#like_button_container');
    if (domContainer) {
      ReactDOM.render(<MyComponent />, domContainer);
    }
  })
  
  document.addEventListener('turbo:render', () => {
    let domContainer = document.querySelector('#like_button_container');
    if (domContainer) {
      ReactDOM.render(<MyComponent />, domContainer);
    }
  })
```

>What I understand is that only stimulus code is automatically re-booted if necessary, but external dependencies are to be either idempotent and booted multiple times, or booted once and hope for no re-render

if that's how about we attached the react component using stimulus controller?

**Comment by james-em** [comment]
One year later, do we have a proper workaround for this? Is turbo really encouraging us to use an event that is fired twice?

Thanks!

**Comment by james-em** [comment]
Still looking for a proper workaround.
Even ugly hacks such as

```
document.addEventListener('turbo:load', () => queryDocumentForTomSelect());
document.addEventListener('turbo:render', () => queryDocumentForTomSelect());
document.addEventListener('turbo:frame-load', () => queryDocumentForTomSelect());
```

Don't work when rendering using turbo-stream with a status of 422 unprocessable_entity
