### ISSUE TITLE
Every single link inside a frame stopped working

### ISSUE THREAD

**Issue by NicosKaralis** [hotwired/turbo#888]
I've updated the turbo gem from 1.3.3 to 1.4 and every single link that is inside a turbo frame does not work anymore

I get `Content missing` now

A very simple example:

- Login page has a turbo-frame with id 'new-session-form'
- Recover password page  page has a turbo-frame with id 'recover-form'

Each page has a link to go back and forth, the link has to be inside the frame because it is located right beside the submit input

Those links do not work anymore, this web app has 2 months and it was working fine, what did I do wrong? what did change? And can I opt out of it to solve it?

**Comment by morgoth** [comment]
I have similar issue after latest upgrade.
In my case:
```
<%= turbo_frame_tag :something do %>
  <%= button_to some_path %>
<% end %>
```
the `some_path` is doing a redirect and I'm getting js error
`Uncaught (in promise) Error: The response (200) did not contain the expected <turbo-frame id="something"> and will be ignored. To perform a full page visit instead, set turbo-visit-control to reload.`

**Comment by kevinmcconnell** [comment]
@NicosKaralis if those links should load new pages (not just replace the particular frame that the link is in) then you should use a `target="_top"` to specify that. (See https://turbo.hotwired.dev/handbook/frames#targeting-navigation-into-or-out-of-a-frame for details and options.)

This has always been how <turbo-frame> elements work. However, in version 7.2 whenever a response didn't have the matching <turbo-frame> element, Turbo would perform a second request to fetch it as a new page. In some cases that can makes the response seem to work, but we found it could also cause other problems, and can mask some errors.

So now in 7.3 we've removed that behaviour of performing the second, full page navigation. It's not a bit more like it used to be before 7.2, however we also show an error message now to try to make the situation clearer.

**Comment by kevinmcconnell** [comment]
We also added a way for certain pages to specify that they should never be rendered into a frame. There's [a new section in the docs](https://turbo.hotwired.dev/handbook/frames#“breaking-out”-from-a-frame) that explains that in more detail.

However in most cases (including what I think you're describing here), the correct fix is to specify where the link or form is targeting, using either `target` or `data-turbo-frame`.

**Comment by kevinmcconnell** [comment]
@morgoth it sounds like your situation is similar. Because your `button_to` is inside a `turbo_frame_tag`, it means the response from submitting that form (after the redirect) is expected to replace only that frame. Because of that, the response needs to contain the matching `<turbo-frame>` element so that Turbo can find the correct content.
 
If you want the form results to replace the whole page instead, you can specify its target as `_top`.

`turbo-visit-control` is useful in the case where you have a page that could potentially be returned from a request inside a frame, but which should replace the entire page if it happens. It's meant more for the cases where that response is unexpected. The most common example we've seen is where you make a frame request but your session has expired, and so the application redirects you to a login page instead. When you have a situation like that, `turbo-visit-control` is something you can add _to that login page_ so that Turbo knows [to treat it differently](https://turbo.hotwired.dev/handbook/frames#“breaking-out”-from-a-frame).

Hope that helps, but please let me know if any of this is still unclear.

**Comment by morgoth** [comment]
@kevinmcconnell Thank you for the explanation.

Indeed setting `<%= button_to "Something", some_path, form: {data: {turbo_frame: "_top"}} %>` fixed it for me.

**Comment by NicosKaralis** [comment]
@kevinmcconnell Thanks for the fast and detailed explanation.

I've added `data: {turbo_frame: "_top"}` to my links, but I feel like the behaviour is not quite the same. I can see some page flickering when updating that I did not see it before

Could be an issue with chrome

<hr>

I'll be closing this as it is already solved
