### ISSUE TITLE
Remove DHH for CoC Violations

### ISSUE THREAD

**Issue by scorbettUM** [hotwired/turbo#977]
I recognize this is going to be stirring the pot, however the manner in which #971 was implemented *directly* violates this project’s own CoC.

![IMG_3503](https://github.com/hotwired/turbo/assets/23642200/451a7b5b-39f6-4e9d-8b41-c560a602b7e2)

I’ve outlined the relevant points above.

#971 was rushed, ignored multiple instances of community feedback, broke countless current PRs and upstream libraries, all because DHH “decided something”. These outcomes are usually avoided by adhering to the CoC, something which also must apply to David.

To @dhh  directly - your actions have yet again caused chaos and harm without care for those who contribute their time to helping further these projects. While open source work should have strong opinions and governance, once other contributors become involved those opinions cease to be the property of a sole individual and deserve proper discussion. Given the childish irresponsibility that drove #971 , I have to ask - did your mother never teach you to share your toys?

Also, “it works at my company”, is not a valid argument. It does not translate to the wider community - much of which uses technology markedly different from yours. 

I have no doubt this will be locked and deleted, but until then, let this serve as a textbook example of poor open source leadership - akin to HashiCorp and Lightbend’s community-hostile decisions. The emperor has no clothes, and one of you needs to tell him.

To the rest of the community appalled at David’s dictatorial behavior, I stand with you and share in your frustrations.

**Comment by Nsttt** [comment]
I absolutely concur with the concerns raised about the implementation of #971. I believe it's essential that every project adheres to its Code of Conduct (CoC), and it appears that there was a misalignment in this regard.

The oversight in community feedback and the ramifications it had on current PRs and libraries are concerning. I respect @dhh for his contributions to the open-source community, but it's imperative to remember that collaboration and feedback are crucial pillars of the community.

Open-source thrives on collective knowledge and shared responsibility. While it's understandable to have strong opinions, open dialogue and discussion should always be at the forefront.

The argument "it works at my company" shouldn’t be the sole reason for implementing a feature, especially if it doesn’t resonate with the broader community.

We're all in this together, and we must remember that respect, collaboration, and mutual understanding will take us further than unilateral decisions.

**Comment by dhh** [comment]
This is elevating a disagreement of a technical decision to a level of nonsense that has no place here. This project has been founded, funded, and maintained predominantly by the resources and investment of 37signals. We will set the direction as we see fit, accepting input and contributions as they're presented, but with no guarantee of concurrence or merging. All the best finding a project that's more to your liking in direction or leadership or otherwise somewhere else 👋

**Comment by dhh** [comment]
This is elevating a disagreement of a technical decision to a level of nonsense that has no place here. This project has been founded, funded, and maintained predominantly by the resources and investment of 37signals. We will set the direction as we see fit, accepting input and contributions as they're presented, but with no guarantee of concurrence or merging. All the best finding a project that's more to your liking in direction or leadership or otherwise somewhere else 👋
